### ISSUE TITLE
TransactionBuilder: Wrong import for Validate.notNull leads to NoClassDefFoundError

### ISSUE THREAD

**Issue by JohannesOehm** [hapifhir/hapi-fhir#2248]
**Describe the bug**
In TransactionBuilder.java, line 134 (addEntryAndReturnRequest function), the method starts with a call to `Validate.notNull(theResource, "theResource must not be null");`. `Validate` is imported from `org.thymeleaf.util`. 

The issue with that is that I get the following error, when Thymeleaf is not in my Classpath: 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/thymeleaf/util/Validate
	at ca.uhn.fhir.util.TransactionBuilder.addEntryAndReturnRequest(TransactionBuilder.java:134)
	at ca.uhn.fhir.util.TransactionBuilder.addCreateEntry(TransactionBuilder.java:116)
	at Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: org.thymeleaf.util.Validate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

I'm using HAPI only as client library. `org.apache.commons.lang3.Validate` seems to be the import, which is mostly used across HAPI code.

**To Reproduce**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>fhir-transactionbuilder-bug</artifactId>
    <version>1.0-SNAPSHOT</version>


    <dependencies>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-structures-r4</artifactId>
            <version>5.2.0</version>
        </dependency>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-client</artifactId>
            <version>5.2.0</version>
        </dependency>
    </dependencies>

</project>
```

```java
import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.util.TransactionBuilder;
import org.hl7.fhir.r4.model.Patient;


public class Main {
    public static void main(String[] args) {
        TransactionBuilder transactionBuilder = new TransactionBuilder(FhirContext.forR4());
        transactionBuilder.addCreateEntry(new Patient());
    }
}
```

**Expected behavior**
I don't get an exception and the Transaction-Bundle is created.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.2.0
 - OS: Windows 10

**Comment by jamesagnew** [comment]
Thanks for the heads up, that was definitely a mistake. It's been fixed.

**Comment by JohannesOehm** [comment]
That's nice to hear. Thank you for your fast response :)
