### ISSUE TITLE
FhirPath creation fails with NoClassDefFoundError: org/fhir/ucum/UcumException

### ISSUE THREAD

**Issue by JohannesOehm** [hapifhir/hapi-fhir#2328]
**Describe the bug**
Hello everybody. I'm getting this error message when I'm trying to use the FhirPath-Engine of HAPI. Maybe there is some dependency missing?

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/fhir/ucum/UcumException
	at org.hl7.fhir.r4.hapi.fluentpath.FhirPathR4.<init>(FhirPathR4.java:22)
	at org.hl7.fhir.r4.hapi.ctx.FhirR4.createFhirPathExecutor(FhirR4.java:46)
	at ca.uhn.fhir.context.FhirContext.newFhirPath(FhirContext.java:705)
	at Main.main(Main.java:6)
Caused by: java.lang.ClassNotFoundException: org.fhir.ucum.UcumException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**To Reproduce**
```
import ca.uhn.fhir.context.FhirContext;

public class Main {
    public static void main(String[] args) {
        final FhirContext fhirContext = FhirContext.forR4();
        fhirContext.newFhirPath();
    }
}
```
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>hapi-fhirpath-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>

        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-client</artifactId>
            <version>5.2.1</version>
        </dependency>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-structures-r4</artifactId>
            <version>5.2.1</version>
        </dependency>

    </dependencies>

</project>
```
**Expected behavior**
No crash

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2.1
 - OS: Windows 10

**Comment by jamesagnew** [comment]
You need to add this dependency to your project:

https://search.maven.org/artifact/org.fhir/ucum/1.0.3/jar
