### ISSUE TITLE
When Validation module is turned on, codes can not be uploaded to terminology service

### ISSUE THREAD

**Issue by gansoper** [hapifhir/hapi-fhir#2402]
**Describe the bug**
I'm using HAPI FHIR 5.0.1. Terminology is turned on, validation module as well. I tried to upload my own codes but got error. After uploading attempt with help of CLI 

java -jar hapi-fhir-cli.jar upload-terminology  -d codes.zip  -t "{FHIRURL}" -v r4 -u "http://test.com/labCodes" 

I got following:

2021-02-19 03:51:52.685 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "att-1: If the Attachment has data, it SHALL have a contentType [data.empty() or contentType.exists()]",
    "location": [ "Parameters.parameter[1].value.ofType(Attachment)", "Line 1, Col 941" ]
  } ]
}
2021-02-19 03:51:52.688 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: att-1: If the Attachment has data, it SHALL have a contentType [data.empty() or contentType.exists()]

**To Reproduce**
1. Turn on Validation Module
2. Turn on Terminology Module
3. Try to upload any codes

**Comment by jamesagnew** [comment]
Are you able to reproduce this on HAPI FHIR 5.3.0?

**Comment by gansoper** [comment]
Tried on 5.3.0  (Starter Example started out of IDE)

2021-02-26 17:32:50.920 [main] INFO  ca.uhn.fhir.jpa.starter.Application [SpringApplication.java:660] No active profile set, falling back to default profiles: default
2021-02-26 17:32:51.608 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate [RepositoryConfigurationDelegate.java:128] Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-02-26 17:32:51.784 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate [RepositoryConfigurationDelegate.java:188] Finished Spring Data repository scanning in 168 ms. Found 47 JPA repository interfaces.
2021-02-26 17:32:52.507 [main] INFO  ca.uhn.fhir.util.VersionUtil [VersionUtil.java:84] **HAPI FHIR version 5.3.0** - Rev 919c1dbddc
2021-02-26 17:32:52.509 [main] INFO  ca.uhn.fhir.context.FhirContext [FhirContext.java:200] Creating new FHIR context for FHIR version [R4]



with CLI 5.3.0

Then CLI

------------------------------------------------------------
?  HAPI FHIR 5.3.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 11496@Lappy
Max configured JVM memory (Xmx) : 4.0GB
Detected Java version           : 11.0.3
------------------------------------------------------------
2021-02-26 17:40:00.483 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: 132_AHANUBCRevenueCodes.zip
2021-02-26 17:40:00.492 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2021-02-26 17:40:01.438 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[Parameters.parameter[1].value.ofType(Attachment), Line 1, Col 9755]</td><td><pre>att-1: 'If the Attachment has data, it SHALL have a contentType' failed</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "att-1: 'If the Attachment has data, it SHALL have a contentType' failed",
    "location": [ "Parameters.parameter[1].value.ofType(Attachment)", "Line 1, Col 9755" ]
  } ]
}
2021-02-26 17:40:01.441 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : att-1: 'If the Attachment has data, it SHALL have a contentType' failed
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:305)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1314)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:204)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:113)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:267)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2021-02-26 17:40:01.442 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
