### ISSUE TITLE
ClassNotFoundException: ca.uhn.fhir.to.TesterConfig

### ISSUE THREAD

**Issue by surendragalwa** [hapifhir/hapi-fhir#2638]
**ClassNotFoundException: ca.uhn.fhir.to.TesterConfig**
When I run my FHIR server test page overlay with IntelliJ Smart Tomcat plugin I always get the following errors:

```
Caused by: java.lang.NoClassDefFoundError: ca/uhn/fhir/to/TesterConfig
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
	... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: ca.uhn.fhir.to.TesterConfig
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1372)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1195)
	... 56 common frames omitted

```

**Expected behavior**
It should start the application without any error

**Screenshots**

**Environment :**
 - HAPI FHIR Version, hapi-fhir-testpage-overlay: 5.1.0
 - OS: Mac
 - Java Version: 8

I am following this guide https://hapifhir.io/hapi-fhir/docs/server_plain/web_testpage_overlay.html

**Comment by jamesagnew** [comment]
You need to ensure that the `-classes` JAR is on your classpath. That's where this class lives. You can download it here: https://repo1.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/5.3.3/

or just add a maven dependency like

```xml
<dependency>
  <groupId>ca.uhn.hapi.fhir</groupId>
  <artifactId>hapi-fhir-testpage-overlay</artifactId>
  <version>5.3.3</version>
  <type>classes</type>
</dependency>
```

**Comment by surendragalwa** [comment]
@jamesagnew I have this dependency in my `pom.xml`

**Comment by jamesagnew** [comment]
You may need to take this up with the developer of the plugin you are using
in that case. The class in question is definitely in that JAR file.
