### ISSUE TITLE
Swagger integration : FhirContext R5 version is not working 

### ISSUE THREAD

**Issue by bshiroya** [hapifhir/hapi-fhir#2727]
Hello 

**Swagger FhirContext R4 version is working but  swagger FhirContext R5 version is not working**

We followed this doc link: https://hapifhir.io/hapi-fhir/docs/server_plain/openapi.html

Kindly please guide me anything missing our integration side 

And We are using java spring boot framework  

Maven lib : hapi-fhir-version : 5.4.0 		

**Error Stacktrace (Using R5 context)**
```

java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "versionString" is null
	at ca.uhn.fhir.context.FhirVersionEnum.forVersionString(FhirVersionEnum.java:240) ~[hapi-fhir-base-5.4.0.jar:na]
	at ca.uhn.fhir.rest.openapi.OpenApiInterceptor.serveSwaggerUiHtml(OpenApiInterceptor.java:288) ~[hapi-fhir-server-openapi-5.4.0.jar:na]
	at ca.uhn.fhir.rest.openapi.OpenApiInterceptor.handleResourceRequest(OpenApiInterceptor.java:227) ~[hapi-fhir-server-openapi-5.4.0.jar:na]
	at ca.uhn.fhir.rest.openapi.OpenApiInterceptor.serveSwaggerUi(OpenApiInterceptor.java:207) ~[hapi-fhir-server-openapi-5.4.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	

```

**Comment by bshiroya** [comment]
@jjathman @preston @dangerousben @karlmdavis any progress?

**Comment by Censacrof** [comment]
I'm also facing the same issue. @bshiroya did you manage to find a solution?

**Comment by bshiroya** [comment]
Yes, we can remove swagger :)
