### ISSUE TITLE
BaseTransactionProcessor throws NullPointerException with versioned references (Automatically Version References)

### ISSUE THREAD

**Issue by patrick-vachon-smilecdr** [hapifhir/hapi-fhir#2901]
We got an issue when trying to save transactional Bundle, returning 500 Server Error with outcome 'Failed to call access method: java.lang.NullPointerException'.

The posted transactional Bundle contains 2 ExplanationOfBenefit, using PUT method as request for both:

```
    "request": {
      "method": "PUT",
      "url": "ExplanationOfBenefit/a25f1c3a-09b9-3f17-8f1b-0fbbf6391fcf"
    }
```

to save ExplanationOfBenefit with specific Id.

If allowing versioned references at all paths, 
and setting 'Automatically Version References at Paths' with some paths:

```
ExplanationOfBenefit.patient ExplanationOfBenefit.insurer ExplanationOfBenefit.provider ExplanationOfBenefit.careTeam.provider ExplanationOfBenefit.insurance.coverage ExplanationOfBenefit.payee.party
```
Also, persistence setting 'Auto-Create Placeholder Reference Targets' was set to true.

Then it makes the 500 error be returned, for ExplanationOfBenefit. All other kind of resources can be saved using transactional Bundle without problem.

That error appears in the logs:
```
2021-08-18 11:21:27.360 [fhir_endpoint.fhirEndpointServer-439] ERROR M:fhir_endpoint R:wQT4rJDlyfcesbjU c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:140] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.jpa.api.model.DaoMethodOutcome.isNop()" because "outcome" is null
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:272)
	at ca.uhn.fhir.rest.server.method.TransactionMethodBinding.invokeServer(TransactionMethodBinding.java:116)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:326)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:434)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1152)
	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:423)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1861)
	at ca.cdr.endpoint.fhir.web.BaseFhirEndpointServlet.service(BaseFhirEndpointServlet.java:500)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at ca.cdr.api.web.BlockVerbsFilter.doFilter(BlockVerbsFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.JettyHealthCheckFilterHttpResponses.doFilter(JettyHealthCheckFilterHttpResponses.java:94)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.endpoint.fhir.web.FhirEndpointElasticApmFilter.doFilter(FhirEndpointElasticApmFilter.java:60)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.endpoint.fhir.web.FhirEndpointErrorTrapFilter.doFilter(FhirEndpointErrorTrapFilter.java:44)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.ExceptionLoggerFilter.doFilter(ExceptionLoggerFilter.java:47)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.DefaultResourcesFilter.doFilter(DefaultResourcesFilter.java:56)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.security.SaveModuleInRequestFilter.doFilter(SaveModuleInRequestFilter.java:73)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.IgnoreInvalidAuthorizationHeaderFilter.doFilter(IgnoreInvalidAuthorizationHeaderFilter.java:50)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.ClearSecurityFilter.doFilter(ClearSecurityFilter.java:22)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.api.web.HttpTroubleshootingLogFilter.doFilter(HttpTroubleshootingLogFilter.java:74)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at ca.cdr.tracing.RequestTracingFilter.doFilter(RequestTracingFilter.java:38)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at ca.cdr.api.web.BaseJettyServer$1.runJob(BaseJettyServer.java:350)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
	... 113 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.jpa.api.model.DaoMethodOutcome.isNop()" because "outcome" is null
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.resolveReferencesThenSaveAndIndexResource(BaseTransactionProcessor.java:1159)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.resolveReferencesThenSaveAndIndexResources(BaseTransactionProcessor.java:1111)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.doTransactionWriteOperations(BaseTransactionProcessor.java:991)
	at ca.uhn.fhir.jpa.dao.TransactionProcessor.doTransactionWriteOperations(TransactionProcessor.java:320)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.lambda$doTransactionWriteOperations$0(BaseTransactionProcessor.java:578)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:147)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:80)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:72)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.doTransactionWriteOperations(BaseTransactionProcessor.java:586)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransaction(BaseTransactionProcessor.java:450)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransactionAsSubRequest(BaseTransactionProcessor.java:299)
	at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.transaction(BaseTransactionProcessor.java:175)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.transaction(BaseHapiFhirSystemDao.java:111)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.transaction(BaseHapiFhirSystemDao.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at ca.cdr.pers.aspect.InvocationCountingAspect.doBasicProfiling(InvocationCountingAspect.java:36)
	at jdk.internal.reflect.GeneratedMethodAccessor257.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy424.transaction(Unknown Source)
	at ca.uhn.fhir.jpa.provider.r4.JpaSystemProviderR4.transaction(JpaSystemProviderR4.java:176)
	... 118 common frames omitted

```

So it looks like BaseTransactionProcessor.resolveReferencesThenSaveAndIndexResource() is producing a NPE when some paths are configured to 'Automatically Version References'.

That is preventing a customer to ingest ExplanationOfBenefit using transactional Bundle and versioning references...

Thank you!

**Comment by patrick-vachon-smilecdr** [comment]
Here is the transactional Bundle:

```
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [ {
    "resource": {
      "resourceType": "ExplanationOfBenefit",
      "id": "26d4cebd-95c6-39ea-855c-dc819bc68d08",
      "meta": {
        "lastUpdated": "2016-01-01T00:56:00.000-05:00",
        "profile": [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Inpatient-Institutional" ]
      },
      "identifier": [ {
        "type": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType",
            "code": "uc"
          } ]
        },
        "system": "fhir/CodeSystem/sid/eob-inpatient-claim-id",
        "value": "20550047"
      } ],
      "status": "active",
      "type": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/claim-type",
          "code": "institutional"
        } ]
      },
      "use": "claim",
      "patient": {
        "reference": "Patient/123"
      },
      "billablePeriod": {
        "start": "2015-12-14T00:00:00-05:00"
      },
      "created": "2021-08-16T13:54:10-04:00",
      "insurer": {
        "reference": "Organization/1"
      },
      "provider": {
        "reference": "Organization/b9d22776-1ee9-3843-bc48-b4bf67861483"
      },
      "outcome": "complete",
      "careTeam": [ {
        "sequence": 1,
        "provider": {
          "reference": "Practitioner/1"
        },
        "role": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/claimcareteamrole",
            "code": "primary"
          } ]
        }
      }, {
        "sequence": 2,
        "provider": {
          "reference": "Practitioner/2"
        },
        "role": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole",
            "code": "attending"
          } ]
        }
      }, {
        "sequence": 3,
        "provider": {
          "reference": "Practitioner/3"
        },
        "role": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole",
            "code": "performing"
          } ]
        }
      } ],
      "supportingInfo": [ {
        "sequence": 1,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "admissionperiod"
          } ]
        },
        "timingPeriod": {
          "start": "2015-12-14T00:00:00-05:00",
          "end": "2016-01-11T14:11:00-05:00"
        }
      }, {
        "sequence": 2,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "clmrecvddate"
          } ]
        },
        "timingDate": "2018-12-23"
      }, {
        "sequence": 3,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "admtype"
          } ]
        },
        "code": {
          "coding": [ {
            "system": "https://www.nubc.org/CodeSystem/PriorityTypeOfAdmitOrVisit",
            "code": "4"
          } ]
        }
      } ],
      "diagnosis": [ {
        "sequence": 1,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "Z38.00"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      } ],
      "insurance": [ {
        "focal": true,
        "coverage": {
          "reference": "Coverage/10"
        }
      } ],
      "total": [ {
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/adjudication",
            "code": "benefit"
          } ]
        },
        "amount": {
          "value": 1039.28
        }
      }, {
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/adjudication",
            "code": "submitted"
          } ]
        },
        "amount": {
          "value": 2011
        }
      } ]
    },
    "request": {
      "method": "PUT",
      "url": "ExplanationOfBenefit/26d4cebd-95c6-39ea-855c-dc819bc68d08"
    }
  }, {
    "resource": {
      "resourceType": "ExplanationOfBenefit",
      "id": "a25f1c3a-09b9-3f17-8f1b-0fbbf6391fce",
      "meta": {
        "lastUpdated": "2016-01-01T00:58:00.000-05:00",
        "profile": [ "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Inpatient-Institutional" ]
      },
      "identifier": [ {
        "type": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType",
            "code": "uc"
          } ]
        },
        "system": "fhir/CodeSystem/sid/eob-inpatient-claim-id",
        "value": "20586901"
      } ],
      "status": "active",
      "type": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/claim-type",
          "code": "institutional"
        } ]
      },
      "use": "claim",
      "patient": {
        "reference": "Patient/123"
      },
      "billablePeriod": {
        "start": "2015-12-18T00:00:00-05:00"
      },
      "created": "2021-08-16T13:54:10-04:00",
      "insurer": {
        "reference": "Organization/1"
      },
      "provider": {
        "reference": "Organization/d10823cf-ee15-3a0e-a12e-1509cd18cda4"
      },
      "outcome": "complete",
      "careTeam": [ {
        "sequence": 1,
        "provider": {
          "reference": "Practitioner/4"
        },
        "role": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/claimcareteamrole",
            "code": "primary"
          } ]
        }
      }, {
        "sequence": 2,
        "provider": {
          "reference": "Practitioner/5"
        },
        "role": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole",
            "code": "attending"
          } ]
        }
      }, {
        "sequence": 3,
        "provider": {
          "reference": "Practitioner/6"
        },
        "role": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBClaimCareTeamRole",
            "code": "performing"
          } ]
        }
      } ],
      "supportingInfo": [ {
        "sequence": 1,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "admissionperiod"
          } ]
        },
        "timingPeriod": {
          "start": "2015-12-18T00:00:00-05:00",
          "end": "2016-01-11T14:12:00-05:00"
        }
      }, {
        "sequence": 2,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "clmrecvddate"
          } ]
        },
        "timingDate": "2018-12-29"
      }, {
        "sequence": 3,
        "category": {
          "coding": [ {
            "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType",
            "code": "admtype"
          } ]
        },
        "code": {
          "coding": [ {
            "system": "https://www.nubc.org/CodeSystem/PriorityTypeOfAdmitOrVisit",
            "code": "4"
          } ]
        }
      } ],
      "diagnosis": [ {
        "sequence": 1,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "Z38.00"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 2,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "P96.89"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 3,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "R25.8"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 4,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "P08.21"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 5,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "P92.5"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 6,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "P92.6"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      }, {
        "sequence": 7,
        "diagnosisCodeableConcept": {
          "coding": [ {
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "code": "Z23"
          } ]
        },
        "type": [ {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
            "code": "principal"
          } ]
        } ]
      } ],
      "insurance": [ {
        "focal": true,
        "coverage": {
          "reference": "Coverage/10"
        }
      } ],
      "total": [ {
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/adjudication",
            "code": "benefit"
          } ]
        },
        "amount": {
          "value": 1421.31
        }
      }, {
        "category": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/adjudication",
            "code": "submitted"
          } ]
        },
        "amount": {
          "value": 2336
        }
      } ]
    },
    "request": {
      "method": "PUT",
      "url": "ExplanationOfBenefit/a25f1c3a-09b9-3f17-8f1b-0fbbf6391fce"
    }
  } ] }
```

Also, persistence setting 'Auto-Create Placeholder Reference Targets' was set to true.

**Comment by tadgh** [comment]
Closed by https://github.com/hapifhir/hapi-fhir/pull/2943
