### ISSUE TITLE
Empty/null username and password in ElasticsearchHibernatePropertiesBuilder throws exception, multiple hosts not possible

### ISSUE THREAD

**Issue by bratwurzt** [hapifhir/hapi-fhir#2975]
When using ElasticsearchHibernatePropertiesBuilder without authentication it throw exception:
```java
Caused by: java.lang.IllegalArgumentException: Username may not be null
	at org.apache.http.util.Args.notNull(Args.java:54) ~[httpcore-4.4.14.jar:4.4.14]
	at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:81) ~[httpclient-4.5.13.jar:4.5.13]
	at ca.uhn.fhir.jpa.search.lastn.ElasticsearchRestClientFactory.createElasticsearchHighLevelRestClient(ElasticsearchRestClientFactory.java:58) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
	at ca.uhn.fhir.jpa.search.elastic.ElasticsearchHibernatePropertiesBuilder.injectStartupTemplate(ElasticsearchHibernatePropertiesBuilder.java:161) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
	at ca.uhn.fhir.jpa.search.elastic.ElasticsearchHibernatePropertiesBuilder.apply(ElasticsearchHibernatePropertiesBuilder.java:102) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
```

1. Use ElasticsearchHibernatePropertiesBuilder to insert properties (kotlin code):
```kotlin
ElasticsearchHibernatePropertiesBuilder()
        .setRestUrl(hapiFhirProperties.elasticsearch.hosts.joinToString(separator = ",") { it })
        .setProtocol(hapiFhirProperties.elasticsearch.protocol)
        .apply(this)
```
**Expected behavior**
Create a HttpClient without credentials

When using ElasticsearchHibernatePropertiesBuilder with multiple hosts, throws exception.

**Comment by tadgh** [comment]
Huh, that's odd. We have a test (see TestR4ConfigWithElasticsearchClient.java L#24) which does exactly this with no issue. Ah wait, come to think of it, it is set to an empty string instead of null. Let me just verify this fix then I'm happy to merge it :)
