### ISSUE TITLE
Batch transaction produces multiple tags in the TAGDEF table, causing IDX_TAGDEF_TYPESYSCODE constraint exceptions

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#3156]
**Describe the bug**
Encountered a race condition, where when a transaction is being processed that has multiple resources with the same tag, occasionally, the tag gets created multiple times in the TAGDEF table. Then, HAPI fails because it expects that the tags in that table be unique.

Here's an example of the exception I'm getting:

```
2021-11-09 00:06:37.591 [http-nio-8080-exec-8] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 1062, SQLState: 23000
2021-11-09 00:06:37.593 [http-nio-8080-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] Duplicate entry '0-https://x.org-y' for key 'IDX_TAGDEF_TYPESYSCODE'
2021-11-09 00:06:37.625 [http-nio-8080-exec-5] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:140] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into hfj_tag_def (tag_code, tag_display, tag_system, tag_type, tag_id) values (?, ?, ?, ?, ?)]; constraint [IDX_TAGDEF_TYPESYSCODE]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:272)
at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154)
at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41)
at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1146)
at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:417)
at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1862)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)
at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)
at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
... 39 common frames omitted
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into hfj_tag_def (tag_code, tag_display, tag_system, tag_type, tag_id) values (?, ?, ?, ?, ?)]; constraint [IDX_TAGDEF_TYPESYSCODE]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessException(HapiFhirHibernateJpaDialect.java:120)
at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessExc...
```

**To Reproduce**
1. Create a large bundle transaction with many resources that have the same tag
2. Execute the transaction bundle
3. Inconsistently and intermittently, it produces an error like shown in the description
4. Look at the HFJ_TAGDEF table and see that the same tag is listed multiple times

**Expected behavior**
A lack should be placed on the TAGDEF table when being modified during the batch transaction, or something, so that it does not produce the same tag multiple times in a single transaction.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.4.1
 - OS: Ubuntu
 - Browser N/A

**Comment by tadgh** [comment]
Heya @seanmcilvenna , we are actively working on this now. Any chance you happen to have a PHI-redacted version of a bundle that causes this for you? Just to ensure we're working under identical conditions? Cheers

**Comment by TipzCM** [comment]
Hi, also, if there's any chance you have additional details (more of the stack trace, etc), it could be helpful.

Or if you have encountered it again lately.

**Comment by dmeyers138** [comment]
Hello,
I can only add that we have the problem as well and it occurs when multithreading, speaks when importing with empty dataset e.g. 4 resources of one type, there are said exceptions. When using a mysql database I could not observe the behavior, only when using a postgresql db. we use ubuntu + hapi 5.5

**Comment by tgorton617** [comment]
I appear to have encountered the same issue, but with multiple single-record POSTs rather than a bundle. here's a short script that inconsistently replicates the issue:

```bash
#!/usr/bin/bash

TAG=tag$RANDOM

for i in {1..5}
do
    FAMILYNAME=Smith$RANDOM
    GIVENNAME=John$RANDOM
    curl \
        https://$SERVER/Patient \
        -X POST \
        --header "Content-Type: application/fhir+json" \
        -w "got %{http_code} - %{time_pretransfer} sec to connect, %{time_starttransfer} sec to respond, %{time_total} sec total \n" \
        -s  \
        --data "{
  \"meta\": {
      \"tag\" : [ 
        {
            \"system\" : \"http://mydomain/fhir/custom_tag/test/$TAG\",
            \"code\" : \"a code\"
        }
    ]
  },
  \"resourceType\": \"Patient\",
  \"name\": [ {
      \"family\": \"$FAMILYNAME\",
      \"given\": [ \"$GIVENNAME\" ]
  } ],
  \"gender\": \"male\",
  \"birthDate\": \"1974-12-25\"
}" \
        --output ./result$i.txt &

done
```

**Comment by XcrigX** [comment]
Still digging into it - but in my case I'm PUTing a Coverage resource in a transaction bundle. The tag already exists in the database.  But as it turns out, the resource I'm PUTing is not valid - when I put it by itself I get an OO showing one of the references is invalid (has spaces in it).  So perhaps in my case something between the parallel transactions when one is failing it affects the checking/inserting into the tag table causing it to try to insert a duplicate record.  
I'll update with more if I find anything useful.
