### ISSUE TITLE
ConcurrentModificiationException in authorization interceptor

### ISSUE THREAD

**Issue by martinvisser** [hapifhir/hapi-fhir#3256]
**Describe the bug**
The moment we add an `AuthorizationInterceptor` which does add checks on compartments a `ConcurrentModificiationException` can occur. We have quite a large `AuthorizationInterceptor` with a lot of rules and therefore hard to figure out which rules might actually be the real trigger. However, it seems to be as soon as such a rule is added:
```kotlin
RuleBuilder()
  .allow("Allow read the current patient QuestionnaireResponses").read()
  .resourcesOfType(QuestionnaireResponse::class.java).inCompartment("Patient", IdDt("Patient", "42"))
  .build()
```

We're not able to reproduce the same issue with HAPI FHIR 5.5.3.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://github.com/martinvisser/hapi-fhir-concurrent
2. Run `./gradlew cleanTest test -i` (the output does create a lot of noise, but multiple stack traces with `ConcurrentModificationException` should be triggered)

**Expected behavior**
Test to succeed without any errors/stack traces.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.6.0 and 5.6.1

**Additional context**
Purely using `RuleBuilder().allowAll().build()` as a rule doesn't trigger the exception, it's only when adding rules on compartments, as is also visible in the stack trace (see below).

The generate stack trace:
```
c.u.f.r.s.i.ExceptionHandlingInterceptor            160 : Failure during REST processing: java.util.ConcurrentModificationException

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at ca.uhn.fhir.util.FhirTerser.isSourceInCompartmentForTarget(FhirTerser.java:753)
	at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRuleToCompartment(RuleImplOp.java:348)
	at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRule(RuleImplOp.java:304)
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndReturnDecision(AuthorizationInterceptor.java:126)
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndFailIfDeny(AuthorizationInterceptor.java:100)
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.checkOutgoingResourceAndFailIfDeny(AuthorizationInterceptor.java:415)
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.hookOutgoingResponse(AuthorizationInterceptor.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService$HookInvoker.invoke(BaseInterceptorService.java:565)
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.doCallHooks(BaseInterceptorService.java:300)
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.callHooks(BaseInterceptorService.java:289)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.callOutgoingResponseHook(BaseResourceReturningMethodBinding.java:495)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:445)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1152)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:413)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
```

**Comment by granadacoder** [comment]
We seem to be experiencing the same issue...since going to HAPI FHIR Version: 5.6.0.
No resolutions yet, we just found it (and found this issue report).

**Comment by jamesagnew** [comment]
I have not been able to reproduce this at all - I notice that the example project is a Kotlin project, maybe it's kotlin specific?

If by any chance anyone can reproduce this in Java that would go a long way towards getting us started on a fix

**Comment by martinvisser** [comment]
Perhaps this is of additional value, which happens during the same test:
```
c.u.f.r.s.i.ExceptionHandlingInterceptor : Failure during REST processing: java.util.ConcurrentModificationException

java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[na:na]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967) ~[na:na]
	at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRuleToCompartment(RuleImplOp.java:402) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRule(RuleImplOp.java:304) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndReturnDecision(AuthorizationInterceptor.java:126) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndFailIfDeny(AuthorizationInterceptor.java:100) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.incomingRequestPreHandled(AuthorizationInterceptor.java:329) ~[hapi-fhir-server-5.6.2.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService$HookInvoker.invoke(BaseInterceptorService.java:565) ~[hapi-fhir-base-5.6.2.jar:na]
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.doCallHooks(BaseInterceptorService.java:300) ~[hapi-fhir-base-5.6.2.jar:na]
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.callHooks(BaseInterceptorService.java:289) ~[hapi-fhir-base-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:256) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:293) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:54) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:326) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:434) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1152) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:413) ~[hapi-fhir-server-5.6.2.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1855) ~[hapi-fhir-server-5.6.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

In both stack traces it happens soon after a call like this:
```java
List<RuntimeSearchParam> params = sourceDef.getSearchParamsForCompartmentName(theCompartmentName);
```

Not saying it is due to that line, but both are loops on `params` where the exception occurs. I do wonder if it might be as simple as doing something like this:
```java
List<RuntimeSearchParam> params = new ArrayList<>(sourceDef.getSearchParamsForCompartmentName(theCompartmentName));
```

I did try it with java and indeed, which you can find in this branch: https://github.com/martinvisser/hapi-fhir-concurrent/tree/java

**Comment by granadacoder** [comment]
Our stacktrace.

```
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
at java.base/java.util.ArrayList$Itr.next(Unknown Source)
at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRuleToCompartment(RuleImplOp.java:402)
at ca.uhn.fhir.rest.server.interceptor.auth.RuleImplOp.applyRule(RuleImplOp.java:304)
at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndReturnDecision(AuthorizationInterceptor.java:126)
at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.applyRulesAndFailIfDeny(AuthorizationInterceptor.java:100)
at ca.uhn.fhir.rest.server.interceptor.auth.AuthorizationInterceptor.incomingRequestPreHandled(AuthorizationInterceptor.java:329)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at ca.uhn.fhir.interceptor.executor.BaseInterceptorService$HookInvoker.invoke(BaseInterceptorService.java:565)
at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.doCallHooks(BaseInterceptorService.java:300)
at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.callHooks(BaseInterceptorService.java:289)
at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:256)
at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:293)
at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:54)
at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:326)
at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:434)
at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1152)
at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:413)
at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1855)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
```

**Comment by martinvisser** [comment]
Just out of curiosity, did the conversion to Java help in investigating the root cause?
