### ISSUE TITLE
Bug: hapi-fhir-cli: (1) docs outdated, (2) can't import any terminologies

### ISSUE THREAD

**Issue by joeflack4** [hapifhir/hapi-fhir#3276]
## Steps to reproduce the behavior:
1. Clone my (ever so slightly changed) hapi-fhir-starter repo: https://github.com/HOT-Ecosystem/hapi-fhir-jpaserver-starter.git
2. Deploy with docker-compose
3. Download terminology files mentioned in docs (I can supply if needed): https://hapifhir.io/hapi-fhir/docs/tools/hapi_fhir_cli.html , and put them in the relative path as shown in the `makefile`
4. Run `make upload-terminology`, which runs commands mentioned in docs.

## Expected behavior
These code systems / terminologies will be uploaded

### 1. Loinc
After about 2 minutes, got error:
```
hapi-fhir-cli upload-terminology -d ./data/value_sets/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip -d /Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/value_sets/terminologies/LOINC/_archive/_Full/Loinc_2.71.zip -v r4 -t http://localhost:8080/fhir -u http://loinc.org
------------------------------------------------------------
🔥  HAPI FHIR 5.6.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 10419@EB-IM-R0KHMD6R.local
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 17.0.1
------------------------------------------------------------
2022-01-05 22:07:23.819 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-01-05 22:07:24.800 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./data/value_sets/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip
2022-01-05 22:07:24.812 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: /Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/value_sets/terminologies/LOINC/_archive/_Full/Loinc_2.71.zip
2022-01-05 22:07:28.577 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2022-01-05 22:07:30.833 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-01-05 22:10:00.222 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown file: hapi-fhir-cli12803979877070915728.zip</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Unknown file: hapi-fhir-cli12803979877070915728.zip"
  } ]
}
2022-01-05 22:10:00.226 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli12803979877070915728.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:305)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1319)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:216)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:123)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:253)
	at ca.uhn.fhir.cli.App.main(App.java:43)
```

### ICD10CM: Only success case
```
hapi-fhir-cli upload-terminology -d ./data/value_sets/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip -d ./data/value_sets/terminologies/ICD-10-CM/icd10cm_tabular_2021.xml -v r4 -t http://localhost:8080/fhir -u http://hl7.org/fhir/sid/icd-10-cm
------------------------------------------------------------
🔥  HAPI FHIR 5.6.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 10576@EB-IM-R0KHMD6R.local
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 17.0.1
------------------------------------------------------------
2022-01-05 22:11:04.228 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-01-05 22:11:05.47 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./data/value_sets/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip
2022-01-05 22:11:05.57 [main] INFO  c.u.f.c.UploadTerminologyCommand Compressing and adding file: ./data/value_sets/terminologies/ICD-10-CM/icd10cm_tabular_2021.xml
2022-01-05 22:11:05.186 [main] INFO  c.u.f.c.UploadTerminologyCommand Finished compressing ./data/value_sets/terminologies/ICD-10-CM/icd10cm_tabular_2021.xml
2022-01-05 22:11:05.188 [main] INFO  c.u.f.c.UploadTerminologyCommand Compressed 8.8 MB bytes in 0 file(s) into 780.7 kB bytes
2022-01-05 22:11:05.188 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-01-05 22:11:07.891 [main] INFO  c.u.f.c.UploadTerminologyCommand Upload complete!
2022-01-05 22:11:07.908 [main] INFO  c.u.f.c.UploadTerminologyCommand Response:
<Parameters xmlns="http://hl7.org/fhir">
   <parameter>
      <name value="success"/>
      <valueBoolean value="true"/>
   </parameter>
   <parameter>
      <name value="conceptCount"/>
      <valueInteger value="45011"/>
   </parameter>
   <parameter>
      <name value="target"/>
      <valueReference>
         <reference value="CodeSystem/1"/>
      </valueReference>
   </parameter>
</Parameters>
2022-01-05 22:11:07.908 [main] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

### SNOMED
```
make upload-snomed
hapi-fhir-cli upload-terminology -d ./data/value_sets/terminologies/SNOMED/SnomedCT_USEditionRF2_PRODUCTION_20210901T120000Z.zip -v r4 -t http://localhost:8080/fhir -u http://snomed.info/sct
------------------------------------------------------------
🔥  HAPI FHIR 5.6.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 11497@EB-IM-R0KHMD6R.local
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 17.0.1
------------------------------------------------------------
2022-01-05 22:25:03.428 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-01-05 22:25:04.332 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./data/value_sets/terminologies/SNOMED/SnomedCT_USEditionRF2_PRODUCTION_20210901T120000Z.zip
2022-01-05 22:25:07.231 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2022-01-05 22:25:08.526 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-01-05 22:25:09.488 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown file: hapi-fhir-cli2959849804250568432.zip</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Unknown file: hapi-fhir-cli2959849804250568432.zip"
  } ]
}
2022-01-05 22:25:09.491 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli2959849804250568432.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:305)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1319)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:216)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:123)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:253)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-01-05 22:25:09.493 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
make: *** [upload-snomed] Error 1
```

## Environment
 - HAPI FHIR Version: R4
 - OS: MacOs 11.4

### Docs are outdated:
https://hapifhir.io/hapi-fhir/docs/tools/hapi_fhir_cli.html

The `-f` flag should be changed to `-v`

### Related issues
This is also about LOINC, but a different error: https://github.com/hapifhir/hapi-fhir/issues/1629

**Comment by joeflack4** [comment]
![ezgif-1-aca0546a61](https://user-images.githubusercontent.com/13045020/154378459-53bd7e18-d0a4-4b72-89a7-35ecacd445de.gif)

**Comment by joeflack4** [comment]
I think it might be a documentation error. I tried with and without, and had an error.

I think my colleague may have been able to successfully import all of these, but only if the upload was executed from the same server that the terminology service is running on. I think that in some cases where we were uploading from our local machine, we would receive an error message telling us that we needed to run on the same server.

Also, I think the SmileCDR documentation might have some better docs for using the `hapi-fhir-cli` than HAPI does.

**Comment by joeflack4** [comment]
Still no luck.

**Comment by joeflack4** [comment]
I also tried using the [SmileCDR docs]([https://smilecdr.com/docs/terminology/uploading.html](https://smilecdr.com/docs/terminology/uploading.html#uploading-external-codesystems)) to try and find a way to use hapi-fhir-cli successfully. For SNOMED, ICD10CM, and LOINC, only had luck w/ LOINC.

I tried doing an extremely simple custom code system (only 2kb, attached), but no luck.

```
make upload-custom1
hapi-fhir-cli upload-terminology -d "/Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/custom1/custom1.zip" -v r4 -t http://20.119.216.32:8888/ts1/fhir -u http://20.119.216.32:8080/fhir/CodeSystem/2
------------------------------------------------------------
🔥  HAPI FHIR 5.7.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : [4975@EB-IM-R0KHMD6R.local](mailto:4975@EB-IM-R0KHMD6R.local)
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 18
------------------------------------------------------------
2022-04-21 21:34:17.982 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-04-21 21:34:18.753 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: /Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/custom1/custom1.zip
2022-04-21 21:34:18.765 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-04-21 21:34:19.107 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 Not Found
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:310)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:376)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:541)
	at ca.uhn.fhir.rest.client.impl.GenericClient$FetchConformanceInternal.execute(GenericClient.java:833)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:311)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:274)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:252)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:541)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1320)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:217)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:124)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:254)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-04-21 21:34:19.108 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
make: *** [upload-custom1] Error 1
```

[custom1.zip](https://github.com/hapifhir/hapi-fhir/files/8536200/custom1.zip)

**Comment by mcabello-cens** [comment]
For me, it works the following things:


**concepts**
CODE,DISPLAY
1,AAAAA
2,BBBBBB

**hierarchy**
PARENT,CHILD
1,2

**Uploading**
hapi-fhir-cli upload-terminology -d custom1.zip -v r4 -t http://localhost:8080/fhir -u http://acme.com/my-own-codesystem

**Comment by joeflack4** [comment]
That looks like almost exactly like my setup.

Did you include the `codesystem.json` that is mentioned in the SmileCDR docs (I don't think normal HAPI has docs for this)? 

It said to include like so:
```json
{
	"resourceType": "CodeSystem",
	"url": "http://20.119.216.32:8080/fhir/CodeSystem/2",
	"name": "Attempt1",
	"description": "I really hope this works",
	"status": "active",
	"publisher": "TIMS",
	"date": "2022-04-21",
	"content": "not-present"
}
```

Otherwise my command is exactly the same as yours / basically the same, depending how you look at it. I wonder if it didn't like one of my params, but it didn't give me any error message to indicate that.

```
hapi-fhir-cli upload-terminology -d "/Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/custom1/custom1.zip" -v r4 -t http://20.119.216.32:8888/ts1/fhir -u http://20.119.216.32:8080/fhir/CodeSystem/2
```

Maybe it didn't like me assigning my own canonical URL like that. Maybe htat's why it gave me:
`ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 Not Found`

Can't check at the moment because I'm not on the right PC, but I suppose I'll try changing that.

@mcabello-cens Do you have a link to your repo/branch? My fork is only from around December 2021, and I haven't updated it since. Perhaps yours is more recent?

**Comment by joeflack4** [comment]
@mcabello-cens For uploading custom CSVs the way you did it, I finally got it to work:
`hapi-fhir-cli upload-terminology -d "/Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/custom1/custom1.zip" -v r4 -t http://20.119.216.32:8080/fhir -u http://20.119.216.32:8080/fhir/CodeSystem/2`

The problem I had with this particular method of uploading custom CSVs was with my CSVs. Somehow when I saved them from Excel, they somehow became tab-separated instead of comma-separated.

There are still issues I'm having with the `hapi-fhir-cli` documentation and upload of SNOMED and LOINC, so I'll leave this issue open.

**Comment by joeflack4** [comment]
@mcabello-cens Let me know if you know someone that I should @ on this topic, as nobody else has responded yet.

I believe that @ShahimEssaid has located the issue.

**Source of the problem**: _`hapi-fhir-cli` is not working well with Docker._

In a private message, he said:
> The CLI creates a /tmp/... .file for local reference for large files and then sends this file path to the server for loading. The server needs to be able to find this file. If the sever is running in docker or some other virtual environment, the CLI and all the needed files have to be in that environment, i.e. in the running docker container of the HAPI server if it's in docker. Otherwise, the /tmp/... path won't work.

I think this explains why I'm getting this as my error:
> ```
> "diagnostics": "Unknown file: hapi-fhir-cli12803979877070915728.zip"
> ```

**Comment by psavva** [comment]
I have run into this exact same problem.
Solution: Create a dockerfile and COPY the HapiFhir CLI together with the terminology files (or alternatively using a volume mount).

The important thing is that the cli and files are accessible within the container.
then run the command directly within the container.

I created a temporary utility container just for this, and uploading of the latest Snomed worked just fine.

My dockerfile:

```
FROM maven:3.8-openjdk-17-slim as build-hapi
WORKDIR /tmp/hapi-fhir-jpaserver-starter

ARG OPENTELEMETRY_JAVA_AGENT_VERSION=1.15.0
RUN curl -LSsO https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OPENTELEMETRY_JAVA_AGENT_VERSION}/opentelemetry-javaagent.jar

COPY pom.xml .
COPY server.xml .
RUN mvn -ntp dependency:go-offline

COPY src/ /tmp/hapi-fhir-jpaserver-starter/src/
COPY src/main/resources/application.yaml /tmp/hapi-fhir-jpaserver-starter/src/main/resources/application.yaml
#COPY src/main/resources/custom.hapi.properties /tmp/hapi-fhir-jpaserver-starter/src/main/resources/custom.hapi.properties
#RUN rm /tmp/hapi-fhir-jpaserver-starter/src/main/resources/application.yaml

RUN mvn clean install -DskipTests -Djdk.lang.Process.launchMechanism=vfork

FROM build-hapi AS build-distroless
RUN mvn package spring-boot:repackage -Pboot
RUN mkdir /app && cp /tmp/hapi-fhir-jpaserver-starter/target/ROOT.war /app/main.war


########### tomcat version is suitable for debugging and comes with a shell
########### it can be built using eg. `docker build --target tomcat .`
FROM tomcat:8.5-jdk11-openjdk-slim as tomcat

RUN mkdir /opt/hapi-cli
COPY hapi-fhir-6.0.1-cli /opt/hapi-cli
######## Note that the hapi-fhir-6.0.1-cli folder also contains my terminology zip files in there...

RUN mkdir /app
WORKDIR /app

COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/target/ROOT.war /usr/local/tomcat/webapps/
COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/opentelemetry-javaagent.jar /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]

```

and finally load it:

java -jar hapi-fhir-cli.jar upload-terminology -v r4 -t http://localhost:8080/fhir -u http://loinc.org -d SnomedCT_InternationalRF2_PRODUCTION_20220731T120000Z.zip

**Comment by joeflack4** [comment]
That would be great.
