### ISSUE TITLE
Socket Timeouts and Blocking Threads

### ISSUE THREAD

**Issue by KevinDougan-SmileCDR** [hapifhir/hapi-fhir#3349]
The Caffeine Caching library that we use (`com.github.benmanes.caffeine.cache.BoundedLocalCache`) has an internal call to `BoundedLocalCache.doComputeIfAbsent()` which is not safely reentrant.  The hashtable needs a global lock to grow in size and can sometimes block all Threads when it resizes the internal storage.

To fix this and make it safely reentrant, change this:
`CachingValidationSupport.loadFromCache()`
to this:
`CachingValidationSupport.loadFromCacheReentrantSafe()`

**Sample BLOCKED Thread from the Thread Dump:**

"XXX_endpoint_r4.fhirEndpointServer-463" id=463 state=BLOCKED- waiting to lock <0x24e533b1> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)owned by XXX_endpoint_r4.fhirEndpointServer-171 id=171at java.base@11.0.13/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1923)at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2029)at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2012)at app//com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)at app//com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)at app//org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.loadFromCache(CachingValidationSupport.java:158)at app//org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.isCodeSystemSupported(CachingValidationSupport.java:117)at app//org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.supportsSystem(VersionSpecificWorkerContextWrapper.java:508)at app//org.hl7.fhir.validation.instance.InstanceValidator.checkCodeableConcept(InstanceValidator.java:1074)at app//org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:4631)at app//org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:4492)at app//org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:4444)at app//org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:4665)at app//org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:4492)at app//org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:4444)at app//org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:4160)at app//org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4023)at app//org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:5242)at app//org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:748)at app//org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:593)at app//org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.validate(ValidatorWrapper.java:181)at app//org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validate(FhirInstanceValidator.java:235)at app//org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:22)at app//org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:45)at app//org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:25)at app//ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:261)at app//ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:202)at app//ca.uhn.fhir.rest.server.interceptor.RequestValidatingInterceptor.doValidate(RequestValidatingInterceptor.java:57)at app//ca.uhn.fhir.rest.server.interceptor.RequestValidatingInterceptor.doValidate(RequestValidatingInterceptor.java:46)at app//ca.uhn.fhir.rest.server.interceptor.BaseValidatingInterceptor.validate(BaseValidatingInterceptor.java:327)at app//ca.uhn.fhir.rest.server.interceptor.RequestValidatingInterceptor.incomingRequestPostProcessed(RequestValidatingInterceptor.java:76)at jdk.internal.reflect.GeneratedMethodAccessor480.invoke(Unknown Source)at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)at app//ca.uhn.fhir.interceptor.executor.BaseInterceptorService$HookInvoker.invoke(BaseInterceptorService.java:565)at app//ca.uhn.fhir.interceptor.executor.BaseInterceptorService.doCallHooks(BaseInterceptorService.java:300)at app//ca.uhn.fhir.interceptor.executor.BaseInterceptorService.callHooks(BaseInterceptorService.java:289)at app//ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1139)at app//ca.uhn.fhir.rest.server.RestfulServer.doPut(RestfulServer.java:428)at app//ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1864)at app//ca.cdr.endpoint.fhir.web.BaseFhirEndpointServlet.service(BaseFhirEndpointServlet.java:509)at app//javax.servlet.http.HttpServlet.service(HttpServlet.java:750)at app//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)at app//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)at app//ca.cdr.api.web.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:72)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.BlockVerbsFilter.doFilter(BlockVerbsFilter.java:51)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)at app//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)at app//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)at app//org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)at app//org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)at app//org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)at app//org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)at app//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)at app//org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)at app//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)at app//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)at app//org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)at app//org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)at app//org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)at app//org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)at app//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.JettyHealthCheckFilterHttpResponses.doFilter(JettyHealthCheckFilterHttpResponses.java:94)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.endpoint.fhir.web.FhirEndpointElasticApmFilter.doFilter(FhirEndpointElasticApmFilter.java:60)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.endpoint.fhir.web.FhirEndpointErrorTrapFilter.doFilter(FhirEndpointErrorTrapFilter.java:44)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.ExceptionLoggerFilter.doFilter(ExceptionLoggerFilter.java:47)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.DefaultResourcesFilter.doFilter(DefaultResourcesFilter.java:56)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.security.SaveModuleInRequestFilter.doFilter(SaveModuleInRequestFilter.java:73)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.IgnoreInvalidAuthorizationHeaderFilter.doFilter(IgnoreInvalidAuthorizationHeaderFilter.java:50)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.ClearSecurityFilter.doFilter(ClearSecurityFilter.java:22)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.api.web.HttpTroubleshootingLogFilter.doFilter(HttpTroubleshootingLogFilter.java:74)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//ca.cdr.tracing.RequestTracingFilter.doFilter(RequestTracingFilter.java:38)at app//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)at app//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)at app//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)at app//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)at app//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)at app//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)at app//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)at app//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)at app//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)at app//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at app//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)at app//org.eclipse.jetty.server.Server.handle(Server.java:516)at app//org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)at app//org.eclipse.jetty.server.HttpChannel$$Lambda$1893/0x0000000841675840.dispatch(Unknown Source)at app//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)at app//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)at app//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)at app//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)at app//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)at app//org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)at app//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)at app//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)at app//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)at app//ca.cdr.api.web.BaseJettyServer$1.runJob(BaseJettyServer.java:369)at app//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)at java.base@11.0.13/java.lang.Thread.run(Thread.java:829)

**Comment by KevinDougan-SmileCDR** [comment]
Closing this as it was already addressed in the following PR (see CachingValidationSupport - Line #144):

https://github.com/hapifhir/hapi-fhir/pull/3236/files
