### ISSUE TITLE
NPE when combining hibernate search and contained resources

### ISSUE THREAD

**Issue by michaelabuckley** [hapifhir/hapi-fhir#3371]
New lucene indexing NPEs with contained resources.

**To Reproduce**
In ModelConfig enable:
- enable `indexOnContainedResources`
- and `indexOnContainedResourcesRecursively`
In DaoConfig enable `advancedLuceneIndexing`
POST /Observation, contained Patient
{
  "resourceType": "Observation",
  "contained": [
    {
      "resourceType": "Patient",
      "id": "contained-patient",
      "name": [{
        "family": "Smith"
      }]
    }
  ],
  "subject": { "reference": "#contained-patient" }
}

**Expected behavior**
200 success

** Actual behaviour**

```
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:149) [4 skipped]
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:83)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:75)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:212)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:192)
... snip ...
**Caused by: org.hibernate.search.util.common.SearchException: HSEARCH700083: Exception while building document for entity 'ResourceTable#1335': HSEARCH600039: Invalid field reference for this document element: this document element has path 'sp.subject.general-practitioner', but the referenced field has a parent with path 'sp'.**
```

Hapi Fair 5.7.0-SNAPSHOT-PRE.

**Comment by michaelabuckley** [comment]
Fixed in  #3372
