### ISSUE TITLE
Pre-expansion fails for ValueSets with more than 1024 concepts 

### ISSUE THREAD

**Issue by jmarchionatto** [hapifhir/hapi-fhir#3421]
**Describe the bug**
When loading a ValueSet which includes more than 1024 concepts, pre-expansion fails for both lucene filesystem and elastic configurations.
The application is generating a search with a match clause per concept.
Possible solutions could be to increase the 1024 limit or to try generating a query with less clauses (maybe a Term query?). 

Errors are shown for both lucene and elastic.

Lucene exception: 
14:13:46.103 [cdr-scheduler-Master-persistence-clustered-2] ERROR M: R: c.u.f.jpa.term.BaseTermReadSvcImpl - Failed to pre-expand ValueSet: maxClauseCount is set to 1024
org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:114)
	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:127)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandValueSetHandleIncludeOrExcludeUsingDatabase(BaseTermReadSvcImpl.java:974) [10 skipped]
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandValueSetHandleIncludeOrExclude(BaseTermReadSvcImpl.java:816)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.lambda$expandValueSet$1(BaseTermReadSvcImpl.java:729)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.lambda$executeInNewTransactionIfNeeded$4(BaseTermReadSvcImpl.java:769)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.executeInNewTransactionIfNeeded(BaseTermReadSvcImpl.java:769) [1 skipped]
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandValueSet(BaseTermReadSvcImpl.java:727)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandValueSet(BaseTermReadSvcImpl.java:702)
	at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.preExpandDeferredValueSetsToTerminologyTables(BaseTermReadSvcImpl.java:1910)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Elastic error:
...
{"match":{"myCode":{"query":"97489-9"}}},{"match":{"myCode":{"query":"97490-7"}}},{"match":{"myCode":{"query":"97491-5"}}},{"match":{"myCode":{"query":"97492-3"}}},{"match":{"myCode":{"query":"97493-1"}}},{"match":{"myCode":{"query":"97494-9"}}},{"match":{"myCode":{"query":"97495-6"}}},{"match":{"myCode":{"query":"97496-4"}}},{"match":{"myCode":{"query":"97497-2"}}},{"match":{"myCode":{"query":"97498-0"}}},{"match":{"myCode":{"query":"98033-4"}}}],"minimum_should_match":"1"}}],"minimum_should_match":"0"}},"_source":false}>. Response body: <{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: maxClauseCount is set to 1024","index_uuid":"kDHEgn_tSv2d0uLEZUxcRw","index":"termconcept-000001"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"termconcept-000001","node":"49beQ-ZiSA-Cd-NI6AbmZg","reason":{"type":"query_shard_exception","reason":"failed to create query: maxClauseCount is set to 1024","index_uuid":"kDHEgn_tSv2d0uLEZUxcRw","index":"termconcept-000001","caused_by":{"type":"too_many_clauses","reason":"maxClauseCount is set to 1024"}}}]},"status":400}>
14:21:48.046 [cdr-scheduler-Master-persistence-clustered-2] ERROR M: R: c.u.f.jpa.term.BaseTermReadSvcImpl - Failed to pre-expand ValueSet: HSEARCH400007: Elasticsearch request failed: HSEARCH400090: Elasticsearch response indicates a failure.
Request: POST /termconcept-read/_search with parameters {from=0, size=800, track_total_hits=false}
Response: 400 'Bad Request' from 'http://localhost:9200' with body 
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: maxClauseCount is set to 1024",
        "index_uuid": "kDHEgn_tSv2d0uLEZUxcRw",
        "index": "termconcept-000001"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "termconcept-000001",
        "node": "49beQ-ZiSA-Cd-NI6AbmZg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: maxClauseCount is set to 1024",
          "index_uuid": "kDHEgn_tSv2d0uLEZUxcRw",
          "index": "termconcept-000001",
          "caused_by": {
            "type": "too_many_clauses",
            "reason": "maxClauseCount is set to 1024"
          }
        }
      }
    ]
  },
  "status": 400
}

**To Reproduce**
Load ValueSet with more than 1024 concepts and wait for pre-expansion to start (triggers every 10 Minutes)

**Expected behavior**
ValueSet should be expanded with no errors.

**Environment (please complete the following information):**
 - HAPI FHIR 6.0.0

**Comment by jmarchionatto** [comment]
Fix merged: https://github.com/hapifhir/hapi-fhir/pull/3434
