### ISSUE TITLE
`MigratePostgresTextClobToBinaryClobTask` fails on PostgresSQL when --dry-run is enabled

### ISSUE THREAD

**Issue by egaga** [hapifhir/hapi-fhir#3445]
When running migration tool on PostgreSQL 11, the migration fails on `NullPointerException`.

**To Reproduce**

- Use PostgreSQL, version 11.
- Have a database initialized by HAPI FIHR 5.1.0
- Run migration tool 5.7 (latest from homebrew)
```
hapi-fhir-cli migrate-database -u "jdbc:postgresql://localhost:5432/<database>" --username "<user>" --password="<password>" --driver=POSTGRES_9_4  --dry-run
```

The migration starts:
```
------------------------------------------------------------
🔥  HAPI FHIR 5.7.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 93023@MACDQBCRMD6M
Max configured JVM memory (Xmx) : 4.0GB
Detected Java version           : 17.0.2
------------------------------------------------------------
2022-03-03 18:59:33.489 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-03-03 18:59:33.607 [main] INFO  c.u.f.j.m.TaskOnlyMigrator Dry run 3_3_0.20180115.0 Initialize schema for HAPI FHIR
2022-03-03 18:59:33.860 [main] INFO  c.u.f.j.m.t.InitializeSchemaTask 3_3_0.20180115.0: The table HFJ_RESOURCE already exists.  Skipping schema initialization for POSTGRES_9_4
2022-03-03 18:59:33.860 [main] INFO  c.u.f.j.m.TaskOnlyMigrator Dry run 3_3_0.20180115.1 Drop column RES_TEXT from table HFJ_RESOURCE
2022-03-03 18:59:33.869 [main] INFO  c.u.f.j.m.t.DropColumnTask 3_3_0.20180115.1: Column RES_TEXT does not exist on table HFJ_RESOURCE - No action performed
```

...Lots of migrations in between...

The error:
```
2022-03-03 18:59:36.984 [main] INFO  c.u.f.j.m.TaskOnlyMigrator Dry run 5_5_0.20211003.1 Migrate text clob SOURCE_DIRECT_PARENT_PIDS from table TRM_VALUESET_CONCEPT (only affects Postgresql)
2022-03-03 18:59:36.992 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.jpa.migrate.JdbcUtils$ColumnType.getColumnTypeEnum()" because "columnType" is null
	at ca.uhn.fhir.jpa.migrate.taskdef.MigratePostgresTextClobToBinaryClobTask.doExecute(MigratePostgresTextClobToBinaryClobTask.java:56)
	at ca.uhn.fhir.jpa.migrate.taskdef.BaseTask.execute(BaseTask.java:214)
	at ca.uhn.fhir.jpa.migrate.TaskOnlyMigrator.migrate(TaskOnlyMigrator.java:60)
	at ca.uhn.fhir.cli.BaseFlywayMigrateDatabaseCommand.run(BaseFlywayMigrateDatabaseCommand.java:142)
	at ca.uhn.fhir.cli.HapiFlywayMigrateDatabaseCommand.run(HapiFlywayMigrateDatabaseCommand.java:56)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:254)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-03-03 18:59:36.992 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```
**Expected behavior**
Migration should succeed.

**Environment**
 - HAPI FHIR Version: Database initialized with 5.1 but command line tool is 5.7.
 - OS: Macos Catalina
 - Postgres 11 https://hub.docker.com/_/postgres

Sidenote: I didn't find anywhere on the site documentation what versions of PostgreSQL are supported.

**Comment by smilenannan** [comment]
@egaga 

I could not find what versions of PostgreSQL are supported either.
So I refer to SmileCDR documentation https://smilecdr.com/docs/getting_started/platform_requirements.html and am using Postgres 12.2. ( it is commercial version, so referring to it makes some sense, I guess )

I run the similar command with yours, in order to migrate from database initialized with v5.0.0 containing some data.
I used CLI tool for v5.7.0.
I did not have any error under these versions.

I hope this finding will help you.

**Comment by egaga** [comment]
@smilenannan Thank you for testing on your system.

I successfully run the migration, too. It might be because I've tried starting up other HAPI-server versions, and maybe the Hibernate auto-ddl is update configuration made some changes to the database that affected it.
Probably need to create afresh and try to retry the original attempt.

**Comment by egaga** [comment]
There doesn't need to be any data.

Just running with `--dry-run` is enough to have the NullPointerException.
Without `--dry-run`, the migration works. However, that's a problem in itself, as I would like to explicitly handle the Flyway migration out of the migration tool.
