### ISSUE TITLE
In hapi 5.7.0 setting setResourceServerIdStrategy(DaoConfig.IdStrategyEnum.UUID) in DaoConfig 

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/hapi-fhir#3462]
**Describe the bug**
If the dao is configured to use resourceServerIdStrategy = DaoConfig.IdStrategyEnum.UUID, then the translateForcedIdToPids in IdHelperService fails because the findAndResolveByForcedIdWithNoType returns an empty collection.

It seems that the lookup may be done before the HFJ_FORCED_ID is populated. 

**To Reproduce**
1. Configure the dao: daoConfig().setResourceServerIdStrategy(DaoConfig.IdStrategyEnum.UUID)
2. Try creating a resource, eg. a CodeSystem
3. See exception:
`ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HAPI-2001: Resource CodeSystem/1 is not known
        at ca.uhn.fhir.jpa.dao.index.IdHelperService.resolveResourceIdentity(IdHelperService.java:143)
        at ca.uhn.fhir.jpa.dao.index.IdHelperService.resolveResourcePersistentIds(IdHelperService.java:184)
        at ca.uhn.fhir.jpa.dao.index.IdHelperService.resolveResourcePersistentIds(IdHelperService.java:215)
        at ca.uhn.fhir.jpa.term.TermCodeSystemStorageSvcImpl.getCodeSystemResourcePid(TermCodeSystemStorageSvcImpl.java:607)
`

**Expected behavior**
That the resource is created and has an id with UUID 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.7.0
 - OS: [e.g. iOS]: Kubernetes/Linux
 - Browser [e.g. chrome, safari]: N/A

**Additional context**

**Comment by jkiddo** [comment]
FYI - Bug is also triggered when installing IG's with `DaoConfig.IdStrategyEnum.UUID` enabled

**Comment by rogtrifork** [comment]
This seems to be caused due to the following:
---
Starting with **5.7.0**, the flow of creating resources changed which seems to have broken **CodeSystem** objects specifically:
In 5.7.0 [**ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao#doCreateForPost**](https://github.com/hapifhir/hapi-fhir/blob/77b4c2a1b11eabc8d08d197353386aa4877137ca/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java#L330) performs the creation in the following steps:
```java
	protected DaoMethodOutcome doCreateForPost(T theResource, String theIfNoneExist, boolean thePerformIndexing, TransactionDetails theTransactionDetails, RequestDetails theRequestDetails) {
                // .... 
                // 1) Calls update where it creates the Resource entry (hfj_resource table)
		ResourceTable updatedEntity = updateEntity(theRequest, theResource, entity, null, thePerformIndexing, false, theTransactionDetails, false, thePerformIndexing);

		// 2) Create forcedId (hfj_forced_id)
		ResourcePersistentId persistentId = new ResourcePersistentId(updatedEntity.getResourceId());
		if (resourceHadIdBeforeStorage) {
			if (resourceIdWasServerAssigned) {
				boolean createForPureNumericIds = true;
				createForcedIdIfNeeded(entity, resourceIdBeforeStorage, createForPureNumericIds, persistentId, theRequestPartitionId);
			} else {
				boolean createForPureNumericIds = getConfig().getResourceClientIdStrategy() != DaoConfig.ClientIdStrategyEnum.ALPHANUMERIC;
				createForcedIdIfNeeded(entity, resourceIdBeforeStorage, createForPureNumericIds, persistentId, theRequestPartitionId);
			}
}
```
While in 5.6.x [**ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao#doCreateForPost**](https://github.com/hapifhir/hapi-fhir/blob/854a84a78ef8fc3f2ec9a297d6f7beccebab188c/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java#L335) this seems to be reversed:
```java
                // 1) Create forcedId (hfj_forced_id)
		boolean serverAssignedId;
		if (isNotBlank(theResource.getIdElement().getIdPart())) {
			if (theResource.getUserData(JpaConstants.RESOURCE_ID_SERVER_ASSIGNED) == Boolean.TRUE) {
				createForcedIdIfNeeded(entity, theResource.getIdElement(), true);
				serverAssignedId = true;
			} else {
				validateResourceIdCreation(theResource, theRequest);
				boolean createForPureNumericIds = getConfig().getResourceClientIdStrategy() != DaoConfig.ClientIdStrategyEnum.ALPHANUMERIC;
				createForcedIdIfNeeded(entity, theResource.getIdElement(), createForPureNumericIds);
				serverAssignedId = false;
			}
		} else {
			serverAssignedId = true;
		}

		// ....

                 // 2) Create the Resource (hfj_resource table)
		ResourceTable updatedEntity = updateEntity(theRequest, theResource, entity, null, thePerformIndexing, false, theTransactionDetails, false, thePerformIndexing);
```
While this does seem to work for other resources, for **CodeSystem** specifically, this seems to cause a problem further down the flow when it tries to perform [**ca.uhn.fhir.jpa.dao.r4.FhirResourceDaoCodeSystemR4#updateEntity**](https://github.com/hapifhir/hapi-fhir/blob/f82534ca5130080f10611582bf4b9888465e5f92/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoCodeSystemR4.java#L165)  where it eventually expects the forcedId to be present already as can be seen in the join statements of [**ca.uhn.fhir.jpa.dao.data.IForcedIdDao#findAndResolveByForcedIdWithNoType**](https://github.com/hapifhir/hapi-fhir/blob/77b4c2a1b11eabc8d08d197353386aa4877137ca/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/IForcedIdDao.java#L54) but since the forcedId does not yet exist, **findAndResolveByForcedIdWithNoType** ends up returning an empty result.
