### ISSUE TITLE
Reindex after upgrading from 6.0.4 to 6.1.0 throws lucene exception

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#3950]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**
1. Upgrade from 6.0.4 to 6.1.0
2. Enable lucene, elastic and resource storage in index e.g.
lastn_enabled: true
store_resource_in_lucene_index_enabled: true
advanced_lucene_indexing: true
3. Run the server

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.1.0 (Latest JPA-Starter)
 - OS: Ubuntu 22.04, OpenJDK 17
 - ES: 7.17.5
 - Browser: NA

**Additional context**
```
2022-08-24 10:19:47.763 [hapi-fhir-jpa-scheduler-clustered-4] ERROR c.u.f.j.s.r.ResourceReindexingSvcImpl [ResourceReindexingSvcImpl.java:357] Failure reindexing
java.util.concurrent.ExecutionException: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl.runReindexJob(ResourceReindexingSvcImpl.java:355)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl.runReindexJobs(ResourceReindexingSvcImpl.java:271)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl.doReindexingPassInsideLock(ResourceReindexingSvcImpl.java:221)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl.runReindexingPass(ResourceReindexingSvcImpl.java:211)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$$FastClassBySpringCGLIB$$f3ca5ded.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$$EnhancerBySpringCGLIB$$566859b9.runReindexingPass(<generated>)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$Job.execute(ResourceReindexingSvcImpl.java:194)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:571)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:152)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$ResourceReindexingTask.readResourceAndReindex(ResourceReindexingSvcImpl.java:506)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$ResourceReindexingTask.call(ResourceReindexingSvcImpl.java:482)
	at ca.uhn.fhir.jpa.search.reindex.ResourceReindexingSvcImpl$ResourceReindexingTask.call(ResourceReindexingSvcImpl.java:467)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
	... 10 common frames omitted
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH700083: Exception while building document for entity 'ResourceTable#112': HSEARCH600074: Multiple values assigned to field 'sp._lastUpdated.dt.lower-ord': this field is single-valued. Declare the field as multi-valued in order to allow this.
Context: path '.myLuceneIndexData'
	at org.hibernate.search.mapper.pojo.work.impl.PojoDocumentContributor.contribute(PojoDocumentContributor.java:56)
	at org.hibernate.search.backend.lucene.document.impl.LuceneIndexEntryFactory.create(LuceneIndexEntryFactory.java:28)
	at org.hibernate.search.backend.lucene.work.execution.impl.LuceneIndexIndexingPlan.addOrUpdate(LuceneIndexIndexingPlan.java:73)
	at org.hibernate.search.mapper.pojo.work.impl.PojoTypeIndexingPlanIndexDelegate.addOrUpdate(PojoTypeIndexingPlanIndexDelegate.java:79)
	at org.hibernate.search.mapper.pojo.work.impl.AbstractPojoTypeIndexingPlan$AbstractEntityState.delegateAddOrUpdate(AbstractPojoTypeIndexingPlan.java:383)
	at org.hibernate.search.mapper.pojo.work.impl.AbstractPojoTypeIndexingPlan$AbstractEntityState.sendCommandsToDelegate(AbstractPojoTypeIndexingPlan.java:322)
	at org.hibernate.search.mapper.pojo.work.impl.AbstractPojoTypeIndexingPlan.process(AbstractPojoTypeIndexingPlan.java:106)
	at org.hibernate.search.mapper.pojo.work.impl.PojoIndexingPlanImpl.process(PojoIndexingPlanImpl.java:138)
	at org.hibernate.search.mapper.orm.event.impl.HibernateSearchEventListener.onFlush(HibernateSearchEventListener.java:199)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1402)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:493)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3285)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2420)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	... 11 common frames omitted
Caused by: org.hibernate.search.mapper.pojo.common.annotation.impl.SearchProcessingWithContextException: HSEARCH600074: Multiple values assigned to field 'sp._lastUpdated.dt.lower-ord': this field is single-valued. Declare the field as multi-valued in order to allow this.
Context: path '.myLuceneIndexData'
	at org.hibernate.search.mapper.pojo.processing.impl.PojoIndexingProcessorPropertyNode.process(PojoIndexingProcessorPropertyNode.java:70)
	at org.hibernate.search.mapper.pojo.processing.impl.PojoIndexingProcessorMultiNode.process(PojoIndexingProcessorMultiNode.java:49)
	at org.hibernate.search.mapper.pojo.processing.impl.PojoIndexingProcessorOriginalTypeNode.process(PojoIndexingProcessorOriginalTypeNode.java:63)
	at org.hibernate.search.mapper.pojo.work.impl.PojoDocumentContributor.contribute(PojoDocumentContributor.java:50)
	... 29 common frames omitted
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH600074: Multiple values assigned to field 'sp._lastUpdated.dt.lower-ord': this field is single-valued. Declare the field as multi-valued in order to allow this.
	at org.hibernate.search.backend.lucene.document.impl.LuceneFlattenedObjectFieldBuilder.checkNoValueYetForSingleValued(LuceneFlattenedObjectFieldBuilder.java:36)
	at org.hibernate.search.backend.lucene.document.impl.AbstractLuceneDocumentElementBuilder.addValue(AbstractLuceneDocumentElementBuilder.java:179)
	at org.hibernate.search.backend.lucene.document.impl.AbstractLuceneDocumentElementBuilder.addValueUnknownType(AbstractLuceneDocumentElementBuilder.java:225)
	at org.hibernate.search.backend.lucene.document.impl.AbstractLuceneDocumentElementBuilder.addValue(AbstractLuceneDocumentElementBuilder.java:86)
	at ca.uhn.fhir.jpa.model.search.HSearchIndexWriter.writeDateIndex(HSearchIndexWriter.java:121)
	at ca.uhn.fhir.jpa.model.search.ExtendedHSearchIndexData.lambda$ifNotContained$0(ExtendedHSearchIndexData.java:68)
	at com.google.common.collect.AbstractMapBasedMultimap.lambda$forEach$2(AbstractMapBasedMultimap.java:1322)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.google.common.collect.AbstractMapBasedMultimap.lambda$forEach$3(AbstractMapBasedMultimap.java:1322)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.google.common.collect.AbstractMapBasedMultimap.forEach(AbstractMapBasedMultimap.java:1321)
	at com.google.common.collect.HashMultimap.forEach(HashMultimap.java:51)
	at ca.uhn.fhir.jpa.model.search.ExtendedHSearchIndexData.writeIndexElements(ExtendedHSearchIndexData.java:100)
	at ca.uhn.fhir.jpa.model.search.SearchParamTextPropertyBinder.write(SearchParamTextPropertyBinder.java:225)
	at ca.uhn.fhir.jpa.model.search.SearchParamTextPropertyBinder.write(SearchParamTextPropertyBinder.java:62)
	at org.hibernate.search.mapper.pojo.processing.impl.PojoIndexingProcessorPropertyBridgeNode.process(PojoIndexingProcessorPropertyBridgeNode.java:45)
	at org.hibernate.search.mapper.pojo.processing.impl.PojoIndexingProcessorPropertyNode.process(PojoIndexingProcessorPropertyNode.java:63)
	... 32 common frames omitted

```

**Comment by azriel-healthpoint** [comment]
Not sure if this is the same issue<sup>1</sup>, but this took me about 4 days to figure out how to solve my version of the error:

```
HAPI-2223:
HSEARCH700083: Exception while building document for entity 'ResourceTable#48032':
HSEARCH600074: Multiple values assigned to field 'sp.latitude.number-value':
this field is single-valued. Declare the field as multi-valued in order to allow this.
```

when I enabled `advanced_lucene_indexing: true`.

My fix was changing the SearchParameter's `expression` [FHIR path](https://hl7.org/fhirpath/#collections) to include ~~`.union({})`~~ `.first()`<sup>2</sup>:

```js
// original SearchParameter expression definition
//
// the `extension('service-location')` is a multi-element in data,
// but HAPI FHIR probably can't tell from this expression, so it
// tells lucene that it's single-valued
"expression": "HealthcareService.extension('http://example.com/').extension('service-location').extension('coordinates').extension('latitude')",

// Add `.first()` to the expression, which only selects the first
// instance of the lower level field.
// This works for my use case where I don't use the latitude field
// in a lucene search.
"expression": "HealthcareService.extension('http://example.com/').extension('service-location').first().extension('coordinates').extension('latitude')",
```


### Footnotes

<sup>1</sup> I searched both this repo and the [hapi-fhir-jpaserver-starter](https://github.com/hapifhir/hapi-fhir-jpaserver-starter) repo to see if the cause was the same, but couldn't find where `_lastUpdated`, `dt`, or `lower-ord` are definted.

<sup>2</sup> I thought `.union({})` worked (where I put `.first()`), but when I re-tested it it in my larger workflow it didn't work 🥲. I *thought* it explicitly tells `BaseSearchParamExtractor` or `SearchParamExtractionUtil` that there will be multiple values for the fields in the remainder of the path.
