### ISSUE TITLE
Elastic search mapper parsing exception when uploading LOINC terminology 

### ISSUE THREAD

**Issue by jmarchionatto** [hapifhir/hapi-fhir#3992]
With elastic search configured as the document indexer and terminology indexing enabled, the following exceptions is thrown when pre-expanding ValueSet(s) after uploading a LOINC version:

2022-09-04 19:14:59.008 [cdr-scheduler-persistence-local-2] INFO  M: R: c.u.f.j.t.TermDeferredStorageSvcImpl - Saved 1000 deferred concepts (416204 codes remain and 350456 relationships remain) in 621ms (1000.0 codes/sec)
Request metadata:
{
  "index": {
    "_index": "termconcept-write",
    "_id": "49109"
  }
}
Response:
{
  "index": {
    "_index": "termconcept-000001",
    "_type": "_doc",
    "_id": "49109",
    "status": 400,
    "error": {
      "type": "mapper_parsing_exception",
      "reason": "The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_objects.limit] index level setting."
    }
  }
}

Failing operation:
Automatic indexing of Hibernate ORM entities
Entities that could not be indexed correctly:
TermConcept#49109
org.hibernate.search.util.common.SearchException: HSEARCH400008: Elasticsearch bulked request failed: HSEARCH400090: Elasticsearch response indicates a failure.
Request metadata:
{
  "index": {
    "_index": "termconcept-write",
    "_id": "49109"
  }
}
Response:
{
  "index": {
    "_index": "termconcept-000001",
    "_type": "_doc",
    "_id": "49109",
    "status": 400,
    "error": {
      "type": "mapper_parsing_exception",
      "reason": "The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_objects.limit] index level setting."
    }
  }
}

        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) [5 skipped]
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [2 skipped]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:649) [1 skipped]
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:383)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH400090: Elasticsearch response indicates a failure.
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) [7 skipped]
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [2 skipped]
        ... 30 common frames omitted

**To Reproduce**
1. Enable elastic search freetext indexing
2. Upload LOINC version 2.72 (should happen with other versions also)
3. Wait for ValueSet pre-expansion (starts right after upload finished)

**Expected behavior**
All ValueSet(s) should be pre-expanded without exceptions.

**Environment**
 - HAPI FHIR Version v6.0.5

**Comment by jmarchionatto** [comment]
Explored how much over 10K nested objects we were talking about, and found out that pretty far. LOINC 2.73 has a TermConcept with 24,528 properties, so raising the default doesn't look like a sensible option for the fix.
