### ISSUE TITLE
Loinc Terminology Upload broken with latest version of Loinc 2.73

### ISSUE THREAD

**Issue by psavva** [hapifhir/hapi-fhir#4000]
**Describe the bug**
Upon uploading the LOINC Terminology Version 2.73, HapiFhir will return an error

```
------------------------------------------------------------
🔥  HAPI FHIR 6.0.1 - Command Line Tool
------------------------------------------------------------
Process ID                      : 262@ehealth4u-fhirserver-cli-8447c85f54-wbft7
Max configured JVM memory (Xmx) : 7.6GB
Detected Java version           : 11.0.16
------------------------------------------------------------
2022-09-07 17:54:21.444 [main] INFO  c.u.f.c.LogbackUtil Logging configuration set from file /logback-cli-on.xml
2022-09-07 17:54:22.543 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: Loinc_2.73.zip
2022-09-07 17:54:22.777 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2022-09-07 17:54:23.14 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-09-07 17:54:28.84 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]"
  } ]
}
2022-09-07 17:54:28.86 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:310)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:376)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:541)
        at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1320)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:217)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:124)
        at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:260)
        at ca.uhn.fhir.cli.App.main(App.java:43)
2022-09-07 17:54:28.88 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

Upon further investigation, I found this announcement from LOINC:
https://loinc.org/component-hierarchy-by-system

> With the release of LOINC version 2.73 in August 2022, the Multiaxial Hierarchy artifact has been renamed Component Hierarchy by System

**To Reproduce**
1. Load Loinc Terminology version 2.73

**Expected behavior**
The Loinc Version 2.73 should be able to load successfully.

**Actual behavior**
The Loinc Version 2.73 fails to load with error: `HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]`

**Environment (please complete the following information):**
 - HAPI FHIR Version: `HAPI FHIR version 6.0.1 - Rev 2a70df1a11`
 - OS: `Kubernetes using Docker image: tomcat:8.5-jdk11-openjdk-slim`
 - Browser: N/A

**Additional context**
We should consider that the solution to this issue must allow for prior versions to be backwards compatible.

**Comment by psavva** [comment]
@jamesagnew  Please do have a look

**Comment by inamullah3344** [comment]
@psavva The main reason for this error is because the name of the hierarchy file and folder have changed in Loinc_2.73 
from  AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv to **AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.csv**

therefore make sure that your LOINC hierarchy file config line looks like this in the /home/smile/smilecdr/terminology/loinc/loincupload.properties                                                                        
loinc.hierarchy.file=AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.csv

then try:

./smileutil upload-terminology -b "user:pass" -t "https://yourFhirServer.com/fhir-request/" -v "r4" -u "http://loinc.org" -d "/Loinc_2.73.zip" -d "/home/smile/smilecdr/terminology/loinc/loincupload.properties"

**Comment by psavva** [comment]
> @psavva The main reason for this error is because the name of the hierarchy file and folder have changed in Loinc_2.73 from AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv to **AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.csv**
> 
> therefore make sure that your LOINC hierarchy file config line looks like this in the /home/smile/smilecdr/terminology/loinc/loincupload.properties loinc.hierarchy.file=AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.csv
> 
> then try:
> 
> ./smileutil upload-terminology -b "user:pass" -t "https://yourFhirServer.com/fhir-request/" -v "r4" -u "http://loinc.org" -d "/Loinc_2.73.zip" -d "/home/smile/smilecdr/terminology/loinc/loincupload.properties"

Reason it doesn't load is clear.

HapiFhir should be adjusted to support the new layout

**Comment by sathishvenkataraman** [comment]
@KevinDougan, I downloaded the docker version today and I got the same issue..  can you please help?

2025-04-10T16:20:11.092Z  INFO 1 --- [           main] ca.uhn.fhir.util.VersionUtil             : HAPI FHIR version 8.0.0 - Rev 091beb6d18
2025-04-10T16:20:11.097Z  INFO 1 --- [           main] ca.uhn.fhir.context.FhirContext          : Creating new FHIR context for FHIR version [R4]

% hapi-fhir-cli upload-terminology -d Loinc_2.80.zip -v r4 -t http://localhost:8080/fhir -u http://loinc.org -s 10GB

2025-04-10 22:14:57.33 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: Loinc_2.80.zip
2025-04-10 22:14:57.99 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2025-04-10 22:15:02.97 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]"
  } ]
}
2025-04-10 22:15:02.97 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:317)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:415)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:585)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1441)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:255)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:151)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:272)
	at ca.uhn.fhir.cli.App.main(App.java:42)
2025-04-10 22:15:02.97 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...

**Comment by KevinDougan** [comment]
@sathishvenkataraman 

See the comment I added to the `loincupload.properties` file here:

https://github.com/hapifhir/hapi-fhir/pull/4382/files#diff-60a3e7884664ef4a11fd3ba8ab976581acee42776e760f88d4396ada0b2f45c0

**Comment by sathishvenkataraman** [comment]
@KevinDougan - Thanks for this!!.. am able to upload Loinc, but for SNOMED it throws heap space error.. inspite of having 8gb XMX and tried beyond that as well..  I tried to split SNOMED then it says imported some of the parts, but I don't see it in db tables like trm_concept etc..

**Comment by preston** [comment]
> [@KevinDougan](https://github.com/KevinDougan) - Thanks for this!!.. am able to upload Loinc, but for SNOMED it throws heap space error.. inspite of having 8gb XMX and tried beyond that as well.. I tried to split SNOMED then it says imported some of the parts, but I don't see it in db tables like trm_concept etc..

The Java heap space issue when setting JAVA_OPTS seems to be caused by the JPA server startup not using it. Set the same JVM arguments via JAVA_TOOL_OPTIONS instead and it should work. I used `JAVA_TOOL_OPTIONS=-Xms1g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200` with SNOMED and HAPI JPA server v8.6.0-1 this morning and it worked.
