### ISSUE TITLE
Batch2 job left in IN_PROGRESS blocks scheduled pre-expansion of ValueSets 

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/hapi-fhir#4206]
We have a terminology service based on hapi-fhir 6.1.0 and observes that a termCodeSystemDeleteJob is stuck in status IN_PROGRESS, but is not progressing. The BaseTermReadSvcImpl schedules a pre-expansion of valuesets every 10th minute, and the execution is being skipped: "Skipping scheduled pre-expansion of ValueSets while deferred entities are being loaded."
The service is unable to recover for days, and there is no access to cancel the failed termCodeSystemDeleteJob except by manual delete of the batch2 status tables (bt2_work_chunk and bt2_job_instance).

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.1.0
 - OS: [e.g. iOS]: linux/K8S
 - Browser [e.g. chrome, safari]: N/A

**Additional context**
Some log inspection has digged out warnings which may be related to the failed job. It is from about the start of the IN_PROGRESS:
```
...

ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child 59c107b1-afc2-400e-a129-f9676a0aa9bf to parent e182c5dc-9f91-474a-92e8-f62be3d498f4 because it appears to have been deleted
-- | --
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child e182c5dc-9f91-474a-92e8-f62be3d498f4 to parent 81c827de-ef31-4410-aa57-0d1d1bc6c264 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child e182c5dc-9f91-474a-92e8-f62be3d498f4 to parent 8addc23a-f7c6-47c4-97fb-a73fcdfc9f65 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child e182c5dc-9f91-474a-92e8-f62be3d498f4 to parent 15846728-58b4-4413-a9d1-be0f1404b10f because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B4 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B3 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B6 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B1 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B2 because it appears to have been deleted
ca.uhn.fhir.jpa.term.TermDeferredStorageSvcImpl | Not inserting link from child B to parent B5 because it appears to have been deleted

...
```
I am not sure if this is signs of database inconsistencies, or just normal behaviour as they are posted as warnings.

**Comment by jamesagnew** [comment]
If you have any steps to reliably reproduce this, or even better a unit test that demonstrates the issue, that would definitely be helpful

**Comment by tyfoni-systematic** [comment]
I have found a scenario that can reproduce failing batch jobs with termCodeSystemVersionDeleteJob. I have a codesystem and execute 2 seperate updates on the codesystem in sequence. This will create 2 jobs (termCodeSystemVersionDeleteJob), but each job will try to delete the same rows in trm_codesystem_ver:
```
2022-11-01 08:36:51.506  INFO 1 [notification-11] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting code system version: 12579
2022-11-01 08:36:51.514  INFO 1 [notification-11] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Code system version: 12579 deleted
...
2022-11-01 08:36:51.731  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting code system version: 12579
2022-11-01 08:36:51.739  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Code system version: 12579 deleted
...
org.springframework.transaction.UnexpectedRollbackException: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: The transaction was set to rollback only
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1038)
...
Caused by: javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?

```
This will leave a batch2 job in status IN_PROGRESS. If there is some delay between the 2 codesystem updates, then the jobs do not overlap, and then both jobs get completed.

The log output from the terminology service:
```
2022-11-01 08:36:48.739  INFO 1 [  XNIO-1 task-3] c.u.f.j.t.TermCodeSystemStorageSvcImpl   : CodeSystem CodeSystem/d44d541e-ce24-41f6-95d7-419ccd34f104/_history/1310 has a status of complete, going to store concepts in terminology tables
2022-11-01 08:36:48.811  INFO 1 [  XNIO-1 task-3] c.u.f.j.t.TermCodeSystemStorageSvcImpl   : Note that some concept saving has been deferred
2022-11-01 08:36:49.234  INFO 1 [  XNIO-1 task-3] c.u.f.j.t.TermCodeSystemStorageSvcImpl   : CodeSystem CodeSystem/d44d541e-ce24-41f6-95d7-419ccd34f104/_history/1311 has a status of complete, going to store concepts in terminology tables
2022-11-01 08:36:49.308  INFO 1 [  XNIO-1 task-3] c.u.f.j.t.TermCodeSystemStorageSvcImpl   : Note that some concept saving has been deferred
2022-11-01 08:36:50.208  INFO 1 [heduler-local-3] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[66f0d900-2126-4a8d-aadb-4df5c42b38e1] step[DeleteCodeSystemVersionFirstStep] chunk[8a4d2ed0-f86a-4976-8469-40210a99e827]
2022-11-01 08:36:50.224  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code links
2022-11-01 08:36:50.228  INFO 1 [heduler-local-3] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[1678e3db-ab3e-48f6-ac3e-47a681d09c38] step[DeleteCodeSystemVersionFirstStep] chunk[4ebae569-14c1-4530-8534-fbab5948eb8d]
2022-11-01 08:36:50.295  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code links
2022-11-01 08:36:50.302  INFO 1 [heduler-local-3] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[b83d0773-a677-4496-bb61-d49d913210ae] step[DeleteCodeSystemVersionFirstStep] chunk[fb135375-842f-4b68-8268-388ddcf3e86e]
2022-11-01 08:36:50.316  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code links
2022-11-01 08:36:50.316  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code properties
2022-11-01 08:36:50.341  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code links
2022-11-01 08:36:50.467  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code links
2022-11-01 08:36:50.467  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code properties
2022-11-01 08:36:50.683  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code links
2022-11-01 08:36:50.683  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting term code properties
2022-11-01 08:36:51.290  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code properties
2022-11-01 08:36:51.291  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concept designations
2022-11-01 08:36:51.353  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 6 concept designations
2022-11-01 08:36:51.353  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concepts
2022-11-01 08:36:51.356  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 8 concepts
2022-11-01 08:36:51.445  INFO 1 [notification-10] c.u.f.b.c.JobStepExecutor                : Gated job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFirstStep produced at most one chunk:  Fast tracking execution.
2022-11-01 08:36:51.445  INFO 1 [notification-10] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[66f0d900-2126-4a8d-aadb-4df5c42b38e1] step[DeleteCodeSystemVersionFinalStep] chunk[cb0df855-84ee-4d89-8a33-5f8040f1faa3]
2022-11-01 08:36:51.506  INFO 1 [notification-11] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting code system version: 12579
2022-11-01 08:36:51.512  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code properties
2022-11-01 08:36:51.513  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concept designations
2022-11-01 08:36:51.514  INFO 1 [notification-11] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Code system version: 12579 deleted
2022-11-01 08:36:51.582  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 concept designations
2022-11-01 08:36:51.582  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concepts
2022-11-01 08:36:51.587  INFO 1 [-notification-9] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 concepts
2022-11-01 08:36:51.662  INFO 1 [-notification-9] c.u.f.b.c.JobStepExecutor                : Gated job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFirstStep produced at most one chunk:  Fast tracking execution.
2022-11-01 08:36:51.662  INFO 1 [-notification-9] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[1678e3db-ab3e-48f6-ac3e-47a681d09c38] step[DeleteCodeSystemVersionFinalStep] chunk[ae3136a2-d3d4-49e5-be29-8abe87fc2b1b]
2022-11-01 08:36:51.725  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 0 term code properties
2022-11-01 08:36:51.725  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concept designations
2022-11-01 08:36:51.731  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting code system version: 12579
2022-11-01 08:36:51.739  INFO 1 [notification-10] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Code system version: 12579 deleted
2022-11-01 08:36:51.760  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 6 concept designations
2022-11-01 08:36:51.760  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting concepts
2022-11-01 08:36:51.763  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleted 7 concepts
2022-11-01 08:36:51.792  INFO 1 [notification-12] c.u.f.b.c.JobStepExecutor                : Gated job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFirstStep produced at most one chunk:  Fast tracking execution.
2022-11-01 08:36:51.792  INFO 1 [notification-12] c.u.f.b.c.BatchJobSender                 : Sending work notification for job[termCodeSystemVersionDeleteJob] instance[b83d0773-a677-4496-bb61-d49d913210ae] step[DeleteCodeSystemVersionFinalStep] chunk[2f6f60aa-cdab-4c78-9a39-620f2294af9c]
2022-11-01 08:36:51.814  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Deleting code system version: 12580
2022-11-01 08:36:51.817  INFO 1 [notification-12] c.u.f.j.t.a.TermCodeSystemDeleteJobSvc   : Code system version: 12580 deleted
2022-11-01 08:36:52.350  INFO 1 [notification-10] o.h.e.j.b.i.AbstractBatchImpl            : HHH000010: On release of batch it still contained JDBC statements
2022-11-01 08:36:52.350 ERROR 1 [notification-10] o.h.e.j.b.i.BatchingBatch                : HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?], SQL: delete from trm_codesystem_ver where pid=?
2022-11-01 08:36:52.352 ERROR 1 [notification-10] c.u.f.b.c.StepExecutionSvc               : Failure executing job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFinalStep
org.springframework.transaction.UnexpectedRollbackException: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: The transaction was set to rollback only
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1038)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.term.api.TermCodeSystemDeleteJobSvc$$EnhancerBySpringCGLIB$$e55326db.deleteCodeSystemVersion(<generated>)
        at ca.uhn.fhir.batch2.jobs.termcodesystem.codesystemversiondelete.DeleteCodeSystemVersionFinalStep.run(DeleteCodeSystemVersionFinalStep.java:50)
        at ca.uhn.fhir.batch2.coordinator.StepExecutionSvc.executeStep(StepExecutionSvc.java:306)
        at ca.uhn.fhir.batch2.coordinator.StepExecutionSvc.doExecution(StepExecutionSvc.java:120)
        at ca.uhn.fhir.batch2.coordinator.JobStepExecutor.executeStep(JobStepExecutor.java:74)
        at ca.uhn.fhir.batch2.coordinator.WorkChannelMessageHandler.handleWorkChannelMessage(WorkChannelMessageHandler.java:94)
        at ca.uhn.fhir.batch2.coordinator.WorkChannelMessageHandler.handleMessage(WorkChannelMessageHandler.java:64)
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.transaction.RollbackException: The transaction was set to rollback only
        at com.atomikos.icatch.jta.TransactionImp.rethrowAsJtaRollbackException(TransactionImp.java:46)
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:182)
        at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:428)
        at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86)
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1035)
        ... 19 more
Caused by: javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3290)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2425)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:356)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.atomikos.icatch.jta.Sync2Sync.beforeCompletion(Sync2Sync.java:34)
        at com.atomikos.icatch.imp.TransactionStateHandler.notifyBeforeCompletion(TransactionStateHandler.java:235)
        at com.atomikos.icatch.imp.TransactionStateHandler.commit(TransactionStateHandler.java:210)
        at com.atomikos.icatch.imp.CompositeTransactionImp.doCommit(CompositeTransactionImp.java:234)
        at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:274)
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:168)
        ... 22 more
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?
        at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
        at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.checkRowCounts(BatchingBatch.java:155)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:130)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:110)
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:633)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        ... 35 more
2022-11-01 08:36:52.359  INFO 1 [notification-11] c.u.f.b.c.JobStepExecutor                : Gated job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFinalStep produced at most one chunk:  Fast tracking execution.
2022-11-01 08:36:52.361  INFO 1 [notification-11] c.u.f.b.p.JobInstanceProgressCalculator  : Job 66f0d900-2126-4a8d-aadb-4df5c42b38e1 of type termCodeSystemVersionDeleteJob has status COMPLETED - 0 records processed (0.0/sec) - ETA: 0ms
2022-11-01 08:36:52.374  INFO 1 [notification-11] c.u.f.b.p.JobInstanceStatusUpdater       : Marking job instance 66f0d900-2126-4a8d-aadb-4df5c42b38e1 of type termCodeSystemVersionDeleteJob as COMPLETED
2022-11-01 08:36:52.380 ERROR 1 [notification-10] f.j.s.c.i.LinkedBlockingChannelFactory$1 : Failure handling message in channel batch2-work-notification
org.springframework.messaging.MessageDeliveryException: Failed to handle ca.uhn.fhir.batch2.model.JobWorkNotificationJsonMessage@5b44092c to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@57d9697c in ca.uhn.fhir.batch2.coordinator.WorkChannelMessageHandler@19814e66; nested exception is ca.uhn.fhir.batch2.api.JobStepFailedException: HAPI-2041: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: The transaction was set to rollback only, failedMessage=ca.uhn.fhir.batch2.model.JobWorkNotificationJsonMessage@5b44092c
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ca.uhn.fhir.batch2.api.JobStepFailedException: HAPI-2041: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: The transaction was set to rollback only
        at ca.uhn.fhir.batch2.coordinator.StepExecutionSvc.executeStep(StepExecutionSvc.java:335)
        at ca.uhn.fhir.batch2.coordinator.StepExecutionSvc.doExecution(StepExecutionSvc.java:120)
        at ca.uhn.fhir.batch2.coordinator.JobStepExecutor.executeStep(JobStepExecutor.java:74)
        at ca.uhn.fhir.batch2.coordinator.WorkChannelMessageHandler.handleWorkChannelMessage(WorkChannelMessageHandler.java:94)
        at ca.uhn.fhir.batch2.coordinator.WorkChannelMessageHandler.handleMessage(WorkChannelMessageHandler.java:64)
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
        ... 3 more
Caused by: org.springframework.transaction.UnexpectedRollbackException: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: The transaction was set to rollback only
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1038)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.term.api.TermCodeSystemDeleteJobSvc$$EnhancerBySpringCGLIB$$e55326db.deleteCodeSystemVersion(<generated>)
        at ca.uhn.fhir.batch2.jobs.termcodesystem.codesystemversiondelete.DeleteCodeSystemVersionFinalStep.run(DeleteCodeSystemVersionFinalStep.java:50)
        at ca.uhn.fhir.batch2.coordinator.StepExecutionSvc.executeStep(StepExecutionSvc.java:306)
        ... 8 more
Caused by: javax.transaction.RollbackException: The transaction was set to rollback only
        at com.atomikos.icatch.jta.TransactionImp.rethrowAsJtaRollbackException(TransactionImp.java:46)
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:182)
        at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:428)
        at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86)
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1035)
        ... 19 more
Caused by: javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3290)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2425)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:356)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.atomikos.icatch.jta.Sync2Sync.beforeCompletion(Sync2Sync.java:34)
        at com.atomikos.icatch.imp.TransactionStateHandler.notifyBeforeCompletion(TransactionStateHandler.java:235)
        at com.atomikos.icatch.imp.TransactionStateHandler.commit(TransactionStateHandler.java:210)
        at com.atomikos.icatch.imp.CompositeTransactionImp.doCommit(CompositeTransactionImp.java:234)
        at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:274)
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:168)
        ... 22 more
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: delete from trm_codesystem_ver where pid=?
        at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
        at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.checkRowCounts(BatchingBatch.java:155)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:130)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:110)
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:633)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        ... 35 more
2022-11-01 08:36:52.578  INFO 1 [notification-12] c.u.f.b.c.JobStepExecutor                : Gated job termCodeSystemVersionDeleteJob step DeleteCodeSystemVersionFinalStep produced at most one chunk:  Fast tracking execution.
2022-11-01 08:36:52.580  INFO 1 [notification-12] c.u.f.b.p.JobInstanceProgressCalculator  : Job b83d0773-a677-4496-bb61-d49d913210ae of type termCodeSystemVersionDeleteJob has status COMPLETED - 0 records processed (0.0/sec) - ETA: 0ms
2022-11-01 08:36:52.590  INFO 1 [notification-12] c.u.f.b.p.JobInstanceStatusUpdater       : Marking job instance b83d0773-a677-4496-bb61-d49d913210ae of type termCodeSystemVersionDeleteJob as COMPLETED
```

**Comment by jamesagnew** [comment]
Awesome, thanks that's helpful. Seeing if I can reproduce.

**Comment by tyfoni-systematic** [comment]
I guess it is some kind of race-condition in the deferred steps. I can't reproduce if I override the number of concurrent consumers (default 4):
```
public class EHealthJpaBatch2Config extends JpaBatch2Config {
    @Override
    protected int getConcurrentConsumers() {
        return 1;
    }
}
```
