### ISSUE TITLE
Large ValueSet expansion failure (core ValueSet body-site)

### ISSUE THREAD

**Issue by psavva** [hapifhir/hapi-fhir#4634]
**Describe the bug**
I'm facing an error when trying to expand the core body-site ValueSet.

Upon executing:
`https://localhost:8080/fhir/ValueSet/body-site/$expand`

The result is:

ValueSet \"ValueSet.url[http://hl7.org/fhir/ValueSet/body-site]\" has not yet been pre-expanded. Performing in-memory expansion without parameters. Current status: NOT_EXPANDED | The ValueSet is waiting to be picked up and pre-expanded by a scheduled task.

with zero results in the response

```
{
  "resourceType": "ValueSet",
  "id": "body-site",
  "meta": {
    "extension": [ {
      "url": ["http://hapifhir.io/fhir/StructureDefinition/valueset-expansion-message"](http://hapifhir.io/fhir/StructureDefinition/valueset-expansion-message),
      "valueString": "ValueSet \"ValueSet.url[http://hl7.org/fhir/ValueSet/body-site]\" has not yet been pre-expanded. Performing in-memory expansion without parameters. Current status: NOT_EXPANDED | The ValueSet is waiting to be picked up and pre-expanded by a scheduled task."
    } ],
    "versionId": "1"
  },
  "url": ["http://hl7.org/fhir/ValueSet/body-site"](http://hl7.org/fhir/ValueSet/body-site),
  "status": "active",
  "compose": {
    "include": [ {
      "system": ["http://snomed.info/sct"](http://snomed.info/sct),
      "filter": [ {
        "property": "concept",
        "op": "is-a",
        "value": "442083009"
      } ]
    } ]
  },
  "expansion": {
    "identifier": "d26a538f-3036-4899-9a67-d06f935ddb8e",
    "timestamp": "2023-03-08T09:43:46+00:00",
    "offset": 0,
    "parameter": [ {
      "name": "offset",
      "valueInteger": 0
    }, {
      "name": "count",
      "valueInteger": 1000
    } ]
  }
}

```

after a few seconds, I notice the following exception in the HapiFhir Logs:

```
2023-03-08 09:45:04.433 [hapi-fhir-jpa-scheduler-clustered-3] INFO  c.uhn.fhir.log.batch_troubleshooting [JobInstanceProgressCalculator.java:68] Job a69bdd2b-611d-41e5-b748-1ddd6d32a86d of type REINDEX has status ERRORED - 457833 records processed (59.53306967987873/sec) - ETA: 0ms
2023-03-08 09:45:04.466 [hapi-fhir-jpa-scheduler-clustered-3] INFO  c.uhn.fhir.log.batch_troubleshooting [JobInstanceProgressCalculator.java:68] Job d667111e-c0df-47c6-837f-c6e5065137f4 of type REINDEX has status ERRORED - 458333 records processed (32.579231385949235/sec) - ETA: 0ms
2023-03-08 09:45:04.469 [hapi-fhir-jpa-scheduler-clustered-3] INFO  c.uhn.fhir.log.batch_troubleshooting [JobInstanceProgressCalculator.java:71] Job fb6d158a-597b-49b8-9233-d9a28a9d5e00 of type termCodeSystemVersionDeleteJob has status IN_PROGRESS - 0 records processed
2023-03-08 09:45:04.473 [hapi-fhir-jpa-scheduler-clustered-3] INFO  o.h.e.j.b.internal.AbstractBatchImpl [AbstractBatchImpl.java:213] HHH000010: On release of batch it still contained JDBC statements
2023-03-08 09:45:04.473 [hapi-fhir-jpa-scheduler-clustered-3] ERROR o.h.e.j.batch.internal.BatchingBatch [BatchingBatch.java:139] HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update bt2_job_instance set job_cancelled=?, cmb_recs_processed=?, cmb_recs_per_sec=?, create_time=?, cur_gated_step_id=?, definition_id=?, definition_ver=?, end_time=?, error_count=?, error_msg=?, est_remaining=?, fast_tracking=?, params_json=?, params_json_lob=?, progress_pct=?, report=?, start_time=?, stat=?, tot_elapsed_millis=?, update_time=?, work_chunks_purged=? where id=? and update_time=?], SQL: update bt2_job_instance set job_cancelled=?, cmb_recs_processed=?, cmb_recs_per_sec=?, create_time=?, cur_gated_step_id=?, definition_id=?, definition_ver=?, end_time=?, error_count=?, error_msg=?, est_remaining=?, fast_tracking=?, params_json=?, params_json_lob=?, progress_pct=?, report=?, start_time=?, stat=?, tot_elapsed_millis=?, update_time=?, work_chunks_purged=? where id=? and update_time=?
2023-03-08 09:45:04.474 [hapi-fhir-jpa-scheduler-clustered-3] ERROR org.quartz.core.JobRunShell [JobRunShell.java:211] Job HAPI.ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl$JobMaintenanceScheduledJob threw an unhandled Exception:
ca.uhn.fhir.rest.server.exceptions.ResourceVersionConflictException: HAPI-0826: The operation has failed with a version constraint failure. This generally means that two clients/threads were trying to update the same resource at the same time, and this request was chosen as the failing request.
        at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessException(HapiFhirHibernateJpaDialect.java:110)
        at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessException(HapiFhirHibernateJpaDialect.java:64)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$EnhancerBySpringCGLIB$$7126f74.updateInstance(<generated>)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$FastClassBySpringCGLIB$$96e41e1a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$EnhancerBySpringCGLIB$$98c23c0e.updateInstance(<generated>)
        at ca.uhn.fhir.batch2.progress.JobInstanceStatusUpdater.updateInstance(JobInstanceStatusUpdater.java:71)
        at ca.uhn.fhir.batch2.progress.JobInstanceStatusUpdater.updateInstanceStatus(JobInstanceStatusUpdater.java:54)
        at ca.uhn.fhir.batch2.progress.JobInstanceProgressCalculator.calculateAndStoreInstanceProgress(JobInstanceProgressCalculator.java:78)
        at ca.uhn.fhir.batch2.maintenance.JobInstanceProcessor.cleanupInstance(JobInstanceProcessor.java:95)
        at ca.uhn.fhir.batch2.maintenance.JobInstanceProcessor.process(JobInstanceProcessor.java:69)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl.doMaintenancePass(JobMaintenanceServiceImpl.java:218)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl.runMaintenancePass(JobMaintenanceServiceImpl.java:199)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl$JobMaintenanceScheduledJob.execute(JobMaintenanceServiceImpl.java:243)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-03-08 09:45:04.474 [hapi-fhir-jpa-scheduler-clustered-3] ERROR org.quartz.core.ErrorLogger [QuartzScheduler.java:2407] Job (HAPI.ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl$JobMaintenanceScheduledJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: ca.uhn.fhir.rest.server.exceptions.ResourceVersionConflictException: HAPI-0826: The operation has failed with a version constraint failure. This generally means that two clients/threads were trying to update the same resource at the same time, and this request was chosen as the failing request.
        at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessException(HapiFhirHibernateJpaDialect.java:110)
        at ca.uhn.fhir.jpa.config.HapiFhirHibernateJpaDialect.convertHibernateAccessException(HapiFhirHibernateJpaDialect.java:64)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$EnhancerBySpringCGLIB$$7126f74.updateInstance(<generated>)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$FastClassBySpringCGLIB$$96e41e1a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at ca.uhn.fhir.jpa.batch2.JpaJobPersistenceImpl$$EnhancerBySpringCGLIB$$98c23c0e.updateInstance(<generated>)
        at ca.uhn.fhir.batch2.progress.JobInstanceStatusUpdater.updateInstance(JobInstanceStatusUpdater.java:71)
        at ca.uhn.fhir.batch2.progress.JobInstanceStatusUpdater.updateInstanceStatus(JobInstanceStatusUpdater.java:54)
        at ca.uhn.fhir.batch2.progress.JobInstanceProgressCalculator.calculateAndStoreInstanceProgress(JobInstanceProgressCalculator.java:78)
        at ca.uhn.fhir.batch2.maintenance.JobInstanceProcessor.cleanupInstance(JobInstanceProcessor.java:95)
        at ca.uhn.fhir.batch2.maintenance.JobInstanceProcessor.process(JobInstanceProcessor.java:69)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl.doMaintenancePass(JobMaintenanceServiceImpl.java:218)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl.runMaintenancePass(JobMaintenanceServiceImpl.java:199)
        at ca.uhn.fhir.batch2.maintenance.JobMaintenanceServiceImpl$JobMaintenanceScheduledJob.execute(JobMaintenanceServiceImpl.java:243)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted

```

**To Reproduce**
1. expand the valueset body-site (note: ensure you have snomed loaded)
2. Notice in-memory expansion does not actually occur
3. Zero results:
```
  "expansion": {
    "identifier": "d26a538f-3036-4899-9a67-d06f935ddb8e",
    "timestamp": "2023-03-08T09:43:46+00:00",
    "offset": 0,
    "parameter": [ {
      "name": "offset",
      "valueInteger": 0
    }, {
      "name": "count",
      "valueInteger": 1000
    } ]
  }
```

**Expected behavior**
The expansion should occur in-memory, and results should return 30K+ results

**Environment (please complete the following information):**
 - HAPI FHIR Version: **6.4.0**
 - OS: Ubuntu/Kubernetes 1.21
 - Browser:  Chrome

**Comment by centaurusgod** [comment]
We encountered the same error, however, after waiting for a while, all the pre-expansion tasks completed successfully, and we were able to expand the value sets as expected.

Additionally, we attempted to invalidate the value set and restart the server. It is unclear which of these actions ultimately resolved the issue.
