### ISSUE TITLE
[R5] Observation creation for Blood Pressure Panel is not working

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#4674]
- HAPI: 6.4.4 (R5)
- Latest JPA Starter

There seems to be a bug in the latest HAPI version when trying to create observations with more than 1 component.
The following Observation fails to create:

`{"resourceType":"Observation","id":"c0229edd-5b71-4e83-9131-30667469e1b1","identifier":[{"use":"official","value":"d5e674483ec237ab60f3af715ade6d8a6b276f188e108ee943530fe0f7c735ec","system":"https://dcmsvdc8gp.hub.doc-cirrus.com/sol/iatros-withings/"}],"code":{"coding":[{"system":"http://loinc.org","code":"85354-9"}]},"category":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"vital-signs"}]}],"status":"registered","subject":{"reference":"Patient/228b7786-e36a-43c2-82ae-aca2d77b4893"},"effectiveDateTime":"2021-12-17T14:56:35.000+01:00","issued":"2023-03-22T16:37:13.787+01:00","extension":[{"url":"obtained-from","valueString":"withings"}],"component":[{"code":{"coding":[{"system":"http://loinc.org","code":"8462-4"}]},"valueQuantity":{"unit":"mmHg","code":"mm[Hg]","value":87,"system":"http://unitsofmeasure.org"}},{"code":{"coding":[{"system":"http://loinc.org","code":"8480-6"}]},"valueQuantity":{"unit":"mmHg","code":"mm[Hg]","value":169,"system":"http://unitsofmeasure.org"}}]}`

It throws the following error on the console:

```
org.hl7.fhir.exceptions.PathEngineException: Attempt to use as on more than one item (2, 'Observation.component.value as Quantity')
	at org.hl7.fhir.r5.utils.FHIRPathEngine.opAs(FHIRPathEngine.java:1821)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1805)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1492)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1474)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:733)
	at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorR5.lambda$getPathValueExtractor$1(SearchParamExtractorR5.java:91)
	at ca.uhn.fhir.jpa.searchparam.extractor.BaseSearchParamExtractor.extractValues(BaseSearchParamExtractor.java:842)
	at ca.uhn.fhir.jpa.searchparam.extractor.BaseSearchParamExtractor.extractSearchParam(BaseSearchParamExtractor.java:1404)
	at ca.uhn.fhir.jpa.searchparam.extractor.BaseSearchParamExtractor.extractSearchParam(BaseSearchParamExtractor.java:1389)
	at ca.uhn.fhir.jpa.searchparam.extractor.BaseSearchParamExtractor.extractSearchParams(BaseSearchParamExtractor.java:1345)
	at ca.uhn.fhir.jpa.searchparam.extractor.BaseSearchParamExtractor.extractSearchParamQuantity(BaseSearchParamExtractor.java:701)
	at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractSearchParamQuantity(SearchParamExtractorService.java:616)
	at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractSearchIndexParameters(SearchParamExtractorService.java:236)
	at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractFromResource(SearchParamExtractorService.java:117)
	at ca.uhn.fhir.jpa.dao.index.SearchParamWithInlineReferencesExtractor.populateFromResource(SearchParamWithInlineReferencesExtractor.java:120)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.updateEntity(BaseHapiFhirDao.java:1012)
```

**Comment by mobilars** [comment]
I have the same problem. Also with blood pressure observation that has multiple components. Using 6.4.4 and R5.

**Comment by mobilars** [comment]
Any news on this issue?

**Comment by ZuSe** [comment]
Works with HAPI 6.6.
Thanks for the fix!
