### ISSUE TITLE
Exception on validation of resources with absolute URLs without Path elements

### ISSUE THREAD

**Issue by alexey-tschudnowsky** [hapifhir/hapi-fhir#5062]
**Describe the bug**
Validation of resources, which have references to external URLs without path (e.g. http://example.org), fails with exception:

`java.lang.StringIndexOutOfBoundsException: String index out of range: 0

	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1512)
	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.fetchStructureDefinition(DefaultProfileValidationSupportBundleStrategy.java:245)
	at ca.uhn.fhir.context.support.DefaultProfileValidationSupport.fetchStructureDefinition(DefaultProfileValidationSupport.java:120)
	at ca.uhn.fhir.context.support.IValidationSupport.fetchResource(IValidationSupport.java:218)
	at org.hl7.fhir.common.hapi.validation.support.ValidationSupportChain.fetchResource(ValidationSupportChain.java:252)
	at org.hl7.fhir.common.hapi.validation.support.BaseValidationSupportWrapper.fetchResource(BaseValidationSupportWrapper.java:62)
	at org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.lambda$fetchResource$8(CachingValidationSupport.java:148)
	at org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.lambda$loadFromCache$17(CachingValidationSupport.java:210)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at ca.uhn.fhir.sl.cache.caffeine.CacheDelegator.get(CacheDelegator.java:41)
	at org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.loadFromCache(CachingValidationSupport.java:211)
	at org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport.fetchResource(CachingValidationSupport.java:147)
	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.lambda$new$0(VersionSpecificWorkerContextWrapper.java:86)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58)
	at ca.uhn.fhir.sl.cache.caffeine.LoadingCacheDelegator.get(LoadingCacheDelegator.java:39)
	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.fetchResource(VersionSpecificWorkerContextWrapper.java:352)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkResourceType(InstanceValidator.java:3637)
	at org.hl7.fhir.validation.instance.InstanceValidator.tryParse(InstanceValidator.java:6369)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkReference(InstanceValidator.java:3346)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:5556)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:5393)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:5341)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:4993)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4786)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6225)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:866)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:718)
	at org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.validate(ValidatorWrapper.java:193)
	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validate(FhirInstanceValidator.java:238)
	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:22)
	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:48)
	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:26)
	at ca.uhn.fhir.validation.FhirValidator.validateResource(FhirValidator.java:342)
	at ca.uhn.fhir.validation.FhirValidator.doValidate(FhirValidator.java:263)
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:236)
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:221)
	at org.hl7.fhir.r4.validation.FhirInstanceValidatorR4Test.testReferencesToNonFHIRExternalUrlsDoNotThrowException(FhirInstanceValidatorR4Test.java:1609)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
`
An example Patient resource [patient-with-reference-to-external-url-without-path.json.txt](https://github.com/hapifhir/hapi-fhir/files/11966062/patient-with-reference-to-external-url-without-path.json.txt) is attached. While the reference used is non FHIR regex compliant, it is still a valid literal reference, see https://www.hl7.org/fhir/references.html#literal especially: 

> Note however, conformance with this regex is no guarantee that the end-point is a FHIR server, and lack of conformance to this regex does not make a reference non-compliant

**To Reproduce**
1. Place the attached example Patient resource to hapi-fhir-validation/src/test/resources/patient-with-reference-to-external-url-without-path.json (remove the .txt ending, which was required only for this bug report!)
1. Add and run the following test to org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java

```
  @ Test
  public void testReferencesToExternalURLsWithoutPathDoNotThrowException() throws IOException {
    final String encoded = loadResource("patient-with-reference-to-external-url-without-path.json");

		final ValidationResult output = myFhirValidator.validateWithResult(encoded);
		final List<SingleValidationMessage> errors = logResultsAndReturnNonInformationalOnes(output);

		errors.stream().forEach(e -> System.out.println(String.format("%s - %s", e.getSeverity(), e.getMessage())));
		assertTrue(errors.isEmpty());
	}
```

3. An exception occurs, while it should not. 

**Expected behavior**
No exception occurs. The validator doesn't produce any issues and the test passes.

**Environment (please complete the following information):**
 - Release 6.6.1 and branch rel_6_6
 - OS: Windows 10 Version 10.0.19045 Build 19045
 - JDK: OpenJDK 17.0.2

**Comment by DarthGizka** [comment]
The bug in [`DefaultProfileValidationSupportBundleStrategy::fetchStructureDefinition`](https://github.com/hapifhir/hapi-fhir/blob/a870d9e6a40f5da49a69b9cecdcfd50fada2e55e/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/support/DefaultProfileValidationSupportBundleStrategy.java#L244-L245) which you fixed in pull request #5063 is only part of the story ...

Some code much higher up the food chain blindly assumes that a value which is found in a field of type `Reference` must be a [FHIR REST URL](https://build.fhir.org/references.html#literal) if it contains more than one slash. It uses a crude heuristic to grab that part of the path which in a FHIR REST URL would be the name of a FHIR resource, without checking whether it has a conformant URL or not. Then it tries to fetch the structure definition for whatever it was it grabbed, which in the case under consideration leads it to try and fetch a structure definition whose name is the empty string.

However, the only actual *requirement* in the standard seems to be that a GET on the URL must return a FHIR resource. Hence the code can only assume that the URL looks like a FHIR REST URL if it happens to look like a FHIR REST URL (e.g. by checking against the regex), not simply based on the fact that it contains more than one slash.

Focal points are `InstanceValidator::tryParse` - which pokes around in the URL instead of parsing it - and `InstanceValidator::checkResourceType`, which abuses `IWorkerContext::fetchResource` to check whether a given string corresponds to a FHIR resource type or not. The test boils down to prepending the given text with "http://hl7.org/fhir/StructureDefinition/" and trying to fetch the structure definition for the result.  Needless to say, this would also classify 'boolean' or 'Address' as resource types.

The irony here is that the code bombs because it fails to check whether a given URL is a FHIR REST URL before assuming that it is, and all this happens while it is essentially trying to find out whether a given URL looks a FHIR REST URL or not.
