### ISSUE TITLE
java.lang.NullPointerException when submitting transaction with identifier._system

### ISSUE THREAD

**Issue by branets-daria** [hapifhir/hapi-fhir#5110]
**Describe the bug**
I receive `500 Internal Server Error`:

> HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke \"String.hashCode()\" because \"this.myUnversionedId\" is null

when trying to submit the following transaction bundle to `POST /`:

```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:d19de503-a8ec-413f-9e45-f52da04dfed4",
            "resource": {
                "resourceType": "Patient",
                "identifier": [
                    {
                        "use": "usual",
                        "_system": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                                    "valueCode": "unknown"
                                }
                            ]
                        },
                        "value": "m123"
                    }
                ],
                "name": [
                    {
                        "text": "Jane Doe"
                    }
                ]
            },
            "request": {
                "method": "POST"
            }
        }
    ]
}
```

The bundle uses `data-absent-reason` extension for identifier system.

If `identifier` uses `system` rather than `_system`, the transaction succeeds:

```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:d19de503-a8ec-413f-9e45-f52da04dfed4",
            "resource": {
                "resourceType": "Patient",
                "identifier": [
                    {
                        "use": "usual",
                        "system": "http://foun.com/identifiers/external",
                        "value": "m123"
                    }
                ],
                "name": [
                    {
                        "text": "Jane Doe"
                    }
                ]
            },
            "request": {
                "method": "POST"
            }
        }
    ]
}
```

If `fullUrl` is not specified, the transaction also succeeds:

```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "resource": {
                "resourceType": "Patient",
                "identifier": [
                    {
                        "use": "usual",
                        "_system": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                                    "valueCode": "unknown"
                                }
                            ]
                        },
                        "value": "m123"
                    }
                ],
                "name": [
                    {
                        "text": "Jane Doe"
                    }
                ]
            },
            "request": {
                "method": "POST"
            }
        }
    ]
}
```

(This is a trimmed-down example, our actual bundles contain multiple resources and we need `fullUrl` to cross-reference them. We also need to specify `system`/`_system` to pass mCODE validation.)

Submitting resource to `POST /Patient` also works successfully.

**Environment:**
 - HAPI FHIR Server - 6.4.0
 - Docker - `hapiproject/hapi:latest`
 - Calls made via Postman

This can also be reproduced on the public HAPI Test Server https://hapi.fhir.org/

![transaction with _system](https://github.com/hapifhir/hapi-fhir/assets/99560040/716b7099-cfe7-4ae3-8cb8-8b6529e37940)

**Comment by smailliwcs** [comment]
Believe the fix would be to `continue` if `nextUriString` is null here:

https://github.com/hapifhir/hapi-fhir/blob/12eb2d6f35dddad35f6128f3aa071157ba8d3d67/hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/BaseTransactionProcessor.java#L1748

As a workaround, we are using a custom `FhirTerser` (provided to the HAPI infrastructure via a custom `FhirContext`) that hides non-empty yet null-valued URIs from the `BaseTransactionProcessor`.  (Technically, we're hiding all such primitive values from any caller of `FhirTerser.getAllPopulatedChildElementsOfType`, so this is significantly more invasive than the direct fix.)

```java
import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.util.FhirTerser;
import org.hl7.fhir.instance.model.api.IBase;
import org.hl7.fhir.instance.model.api.IBaseResource;
import org.hl7.fhir.instance.model.api.IPrimitiveType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Iterator;
import java.util.List;

public class CustomFhirTerser extends FhirTerser {
    private static final Logger logger = LoggerFactory.getLogger(CustomFhirTerser.class);

    public CustomFhirTerser(FhirContext fhirContext) {
        super(fhirContext);
    }

    @Override
    public <T extends IBase> List<T> getAllPopulatedChildElementsOfType(IBaseResource resource, Class<T> elementType) {
        List<T> elements = super.getAllPopulatedChildElementsOfType(resource, elementType);
        for (Iterator<T> iterator = elements.iterator(); iterator.hasNext(); ) {
            T element = iterator.next();
            if (!(element instanceof IPrimitiveType)) {
                continue;
            }
            IPrimitiveType<?> primitive = (IPrimitiveType<?>) element;
            if (primitive.getValueAsString() == null) {
                logger.warn("Suppressing null element: {}", primitive.getClass().getName());
                iterator.remove();
            }
        }
        return elements;
    }
}
```

**Comment by ryckbirch** [comment]
The behavior has changed at least by v6.10. The issue was indeed in the terser functionality and specifically with a coded choice to NOT descend into child objects. In the 6.4 code base FhirTerser.java has code around line 1051 as follows

```							if (nextChild instanceof RuntimeChildDirectResource) {
								// Don't descend into embedded resources
								theCallback.acceptElement(theResource, nextValue, null, nextChild, childElementDef);
							} else {
								visit(theStack, theResource, nextValue, pathToElement, nextChild, childElementDef, theCallback);
							}
```
The refusal to descend let's the urlType have nulls and hence the issue. v6.10 code changes and this issue is now handled.

**Comment by smailliwcs** [comment]
Hmm, I'm still seeing this on the latest JPA server.  Minimal repro:

```sh
#!/bin/bash

docker run -p 8080:8080 -d hapiproject/hapi:latest
sleep 30

curl -X PUT 'http://localhost:8080/fhir/Patient/john-doe' \
    -H 'Content-Type: application/fhir+xml' \
    --data-binary @- << EOF
<Patient xmlns="http://hl7.org/fhir">
    <id value="john-doe"/>
    <identifier>
        <system>
            <extension url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
                <valueCode value="unknown"/>
            </extension>
        </system>
    </identifier>
</Patient>
EOF

curl -X POST 'http://localhost:8080/fhir' \
    -H 'Content-Type: application/fhir+xml' \
    --data-binary @- << EOF
<Bundle xmlns="http://hl7.org/fhir">
    <type value="batch"/>
    <entry>
        <fullUrl value="http://example.com/fhir/Patient/john-doe"/>
        <resource>
            <Patient xmlns="http://hl7.org/fhir">
                <id value="john-doe"/>
                <identifier>
                    <system>
                        <extension url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
                            <valueCode value="unknown"/>
                        </extension>
                    </system>
                </identifier>
            </Patient>
        </resource>
        <request>
            <method value="PUT"/>
            <url value="Patient/john-doe"/>
        </request>
    </entry>
</Bundle>
EOF
```

The first request succeeds.  The second one (identical except for the fact that it's in a batch bundle) fails with the following stack trace:

```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "this.myUnversionedId" is null
        at ca.uhn.fhir.jpa.dao.IdSubstitutionMap$Entry.hashCode(IdSubstitutionMap.java:119)
        at java.base/java.util.HashMap.hash(HashMap.java:338)
        at java.base/java.util.HashMap.getNode(HashMap.java:568)
        at java.base/java.util.HashMap.containsKey(HashMap.java:594)
        at ca.uhn.fhir.jpa.dao.IdSubstitutionMap.containsSource(IdSubstitutionMap.java:46)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.resolveReferencesThenSaveAndIndexResource(BaseTransactionProcessor.java:1744)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.resolveReferencesThenSaveAndIndexResources(BaseTransactionProcessor.java:1597)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.doTransactionWriteOperations(BaseTransactionProcessor.java:1327)
        at ca.uhn.fhir.jpa.dao.TransactionProcessor.doTransactionWriteOperations(TransactionProcessor.java:166)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.lambda$prepareThenExecuteTransactionWriteOperations$1(BaseTransactionProcessor.java:686)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:395)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteInTransaction(HapiTransactionService.java:276)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecute(HapiTransactionService.java:253)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder.execute(HapiTransactionService.java:479)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.prepareThenExecuteTransactionWriteOperations(BaseTransactionProcessor.java:707)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransaction(BaseTransactionProcessor.java:538)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransactionAsSubRequest(BaseTransactionProcessor.java:359)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor$RetriableBundleTask.processBatchEntry(BaseTransactionProcessor.java:2157)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor$RetriableBundleTask.processBatchEntryWithRetry(BaseTransactionProcessor.java:2178)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor$RetriableBundleTask.run(BaseTransactionProcessor.java:2198)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.batch(BaseTransactionProcessor.java:407)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransaction(BaseTransactionProcessor.java:457)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.processTransactionAsSubRequest(BaseTransactionProcessor.java:359)
        at ca.uhn.fhir.jpa.dao.BaseTransactionProcessor.transaction(BaseTransactionProcessor.java:206)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.transaction(BaseHapiFhirSystemDao.java:176)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.transaction(BaseHapiFhirSystemDao.java:74)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao$$FastClassBySpringCGLIB$$24ad6266.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at ca.uhn.fhir.jpa.dao.r4.FhirSystemDaoR4$$EnhancerBySpringCGLIB$$a3734829.transaction(<generated>)
        at ca.uhn.fhir.jpa.provider.JpaSystemProvider.transaction(JpaSystemProvider.java:139)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
        at ca.uhn.fhir.rest.server.method.TransactionMethodBinding.invokeServer(TransactionMethodBinding.java:119)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:146)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:275)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1190)
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:432)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1929)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ryckbirch** [comment]
@smailliwcs The scenarios are slightly different. @jamesagnew Thank you, sir!
