### ISSUE TITLE
Remove Caffeine dependency from hapi-fhir-validation

### ISSUE THREAD

**Issue by vitorpamplona** [hapifhir/hapi-fhir#5348]
**Describe the bug**

Caffeine is already being imported from `hapi-fhir-serviceloaders`/`hapi-fhir-caching-caffeine` and will be swapped by Guava when used on Android. 

This direct dependency should then be removed: https://github.com/hapifhir/hapi-fhir/blob/743e2c178b2a7f6212e537270114d4428b7a9558/hapi-fhir-validation/pom.xml#L106

**Comment by jy95** [comment]
Will it be also helpful for this kind of issues ?

```bash
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: HAPI-2200: No Cache Service Providers found. Choose between hapi-fhir-caching-caffeine (Default) and hapi-fhir-caching-guava (Android) [in thread "ForkJoinPool.commonPool-worker-1"]
        at ca.uhn.fhir.sl.cache.CacheFactory.getCacheProvider(CacheFactory.java:41)
        at ca.uhn.fhir.sl.cache.CacheFactory.build(CacheFactory.java:46)
        at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.<init>(HapiWorkerContext.java:89)
        at org.hl7.fhir.r4.hapi.fluentpath.FhirPathR4.<init>(FhirPathR4.java:31)
        at org.hl7.fhir.r4.hapi.ctx.FhirR4.createFhirPathExecutor(FhirR4.java:56)
        at ca.uhn.fhir.context.FhirContext.newFhirPath(FhirContext.java:890)
```

Kind regards
