### ISSUE TITLE
InvalidPathException: Illegal char <:> at index 5: https://hos... at ca.uhn.fhir.util.UrlUtil.getAboveUriCandidates() 

### ISSUE THREAD

**Issue by bdenton** [hapifhir/hapi-fhir#5364]
**Describe the bug**
The `getAboveUriCandidates()` of `ca.uhn.fhir.util.UrlUtil` throws an InvalidPathException when passed a http URL. This is due to an improper use of the `Paths.get()` method.

**To Reproduce**
1. Go to `hapi-fhir-structures-r4`
2. Run `mvn test`
3. See errors and stack traces for test cases in `ca.uhn.fhir.util.UrlUtilTest` test class

**Expected behavior**
The `ca.uhn.fhir.util.UrlUtilTest` test class should execute successfully

**Screenshots**
```
[INFO] Running ca.uhn.fhir.util.UrlUtilTest
[ERROR] Tests run: 32, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.205 s <<< FAILURE! - in ca.uhn.fhir.util.UrlUtilTest
[ERROR] ca.uhn.fhir.util.UrlUtilTest.testGetAboveUriCandidates_withFullUri_returnsUriList  Time elapsed: 0.015 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://host.com:8080/path1/path2?name=name#name
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at ca.uhn.fhir.util.UrlUtil.getAboveUriCandidates(UrlUtil.java:626)
        at ca.uhn.fhir.util.UrlUtilTest.testGetAboveUriCandidates_withFullUri_returnsUriList(UrlUtilTest.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.9.10-SNAPSHOT (commit c832cf0)
 - OS: Windows 10; java version "17.0.4.1" 2022-08-18 LTS; Maven 3.8.6
 - Browser: n/a

**Additional context**
Based on Java 17 Javadocs (and looking at the code for `Paths.get()` and `Path.of()`), it would appear that `Paths.get()` will only resolve against a "file system". On WIndows, this always results in a call to `WindowsFileSystem`.. Suggestion would be to manually split up the URI instead of using `Paths.get()`

**Comment by bdenton** [comment]
How is this method really supposed to work?
- Comments in the method say:
```
	 * Example input: http://[host]/[pathPart1]/[pathPart2]
	 * Example output: http://[host], http://[host]/[pathPart1], http://[host]/[pathPart1]/[pathPart2]
```
- Code in the R4 test `UrlUtilTest` says that for input `https://host.com:8080/path1/path2?name=name#name` that one of the results should also be "https://host.com:8080/path1/path2?name=name#name" complete with query string and fragment.

Which is is supposed to be?
