### ISSUE TITLE
Version Canonicalizer fails for CapabilityStatement with FHIR DSTU2

### ISSUE THREAD

**Issue by codeforgreen** [hapifhir/hapi-fhir#5431]
**Describe the bug**

**To Reproduce**
```
Caused by: java.lang.IllegalArgumentException: HAPI-1829: This parser is for FHIR version DSTU2 - Can not encode a structure for version DSTU2_HL7ORG
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:338)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:298)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:286)
	at ca.uhn.hapi.converters.canonical.VersionCanonicalizer$Dstu2Strategy.reencodeToHl7Org(VersionCanonicalizer.java:526)
	at ca.uhn.hapi.converters.canonical.VersionCanonicalizer$Dstu2Strategy.capabilityStatementFromCanonical(VersionCanonicalizer.java:517)
	at ca.uhn.hapi.converters.canonical.VersionCanonicalizer.capabilityStatementFromCanonical(VersionCanonicalizer.java:147)
```

**Comment by codeforgreen** [comment]
https://github.com/hapifhir/hapi-fhir/pull/5432
