### ISSUE TITLE
NumberFormatException when updating an MDM link with UUID resource IDs

### ISSUE THREAD

**Issue by LJNIC** [hapifhir/hapi-fhir#5590]
**Describe the bug**
A NumberFormatException is thrown when updating an MDM link when UUID resource IDs are enabled.

**To Reproduce**
1. Enable MDM
2. Set JpaStorageSettings server id strategy to "UUID"
3. POST an MDM-enabled resource
4. Update the link to NO MATCH
5. Exception is thrown

**Expected behavior**
For there not to be an exception.

**Screenshots**
```
Caused by: java.lang.NumberFormatException: For input string: "d4a31ac5-d8c7-4bd5-a331-a9cc94656a75"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at ca.uhn.fhir.jpa.dao.index.IdHelperService.newPidFromStringIdAndResourceName(IdHelperService.java:822)
	at ca.uhn.fhir.jpa.dao.index.IdHelperService.newPidFromStringIdAndResourceName(IdHelperService.java:99)
	at ca.uhn.fhir.mdm.svc.MdmSurvivorshipSvcImpl.getResourcePID(MdmSurvivorshipSvcImpl.java:146)
	at ca.uhn.fhir.mdm.svc.MdmSurvivorshipSvcImpl.lambda$getMatchedSourceIdsByLinkUpdateDate$1(MdmSurvivorshipSvcImpl.java:136)
```

**Environment (please complete the following information):**
 - HAPI FHIR 6.10.2

**Comment by LJNIC** [comment]
Follow-up: are UUIDs even intended to be used?

**Comment by michealharrington** [comment]
Bump on this, any updates?
