### ISSUE TITLE
Expunging deleted resources fails due to SQL constraint

### ISSUE THREAD

**Issue by vilaug** [hapifhir/hapi-fhir#5728]
**Describe the bug**
Expunging deleted resources fails due to:
```
c.u.f.r.s.e.InternalErrorException: HAPI-1085: java.util.concurrent.ExecutionException: ca.uhn.fhir.rest.server.exceptions.ResourceVersionConflictException: HAPI-0550: HAPI-2223: could not execute statement; SQL [n/a]; constraint [fk_resparmpres_resid]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at c.u.f.j.d.e.PartitionRunner.runInPartitionedThreads(PartitionRunner.java:123)
	at c.u.f.j.d.e.ExpungeOperation.deleteCurrentVersionsOfDeletedResources(ExpungeOperation.java:125)
	at c.u.f.j.d.e.ExpungeOperation.expungeDeletedResources(ExpungeOperation.java:93)
	at c.u.f.j.d.e.ExpungeOperation.call(ExpungeOperation.java:69)
	at c.u.f.j.d.e.ExpungeService.expunge(ExpungeService.java:64)
	at n.i.f.s.c.e.DeletedResourceExpungeCron.expungeDeletedResources(DeletedResourceExpungeCron.java:40)
	at j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j.l.reflect.Method.invoke(Method.java:568)
	at o.s.s.s.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at o.s.s.s.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at o.s.s.c.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:539)
	at j.u.c.FutureTask.run(FutureTask.java:264)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**
Not sure if this is a problem with the database, or something else, but the preconditions seem to be:
1. Have an entry for a deleted resource in the `hfj_res_param_present` table
2. Run the the expunge job with `expungeDeleteResources: true` and other params set to false.

**Expected behavior**
1. I'd expect that the expunge job succeeds, the underlying issue might be that the `res_param_present` entry is not deleted when a resource is deleted. 

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.6.2

**Comment by vilaug** [comment]
We experience the issue in several FHIR servers and I can see a lot of hfj_res_param_present entries for deleted resources. If anyone has any pointers for further investigation, I'd gladly look into it.

**Comment by jamesagnew** [comment]
As a first step, can you please verify whether this is still happening against the current release of HAPI FHIR? (7.0.0)

**Comment by vilaug** [comment]
Hi @jamesagnew, we'll schedule an upgrade and will get back on this then.
