### ISSUE TITLE
ClassCast exception arises when loading in implementation guide.

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir#5834]
at https://github.com/hapifhir/hapi-fhir/blob/107de2cfba04691ec085453062ee98f7200d7a4e/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/JpaPackageCache.java#L407 - the following bug occur with stacktrace (from HAPI FHIR JPA starter):

```
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:488)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restfulServer' defined in class path resource [ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.class]: Unsatisfied dependency expressed through method 'restfulServer' parameter 25: Error creating bean with name 'packageInstaller' defined in class path resource [ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.class]: Failed to instantiate [ca.uhn.fhir.jpa.packages.IPackageInstallerSvc]: Factory method 'packageInstaller' threw exception with message: class org.hl7.fhir.r4.model.Device$DeviceVersionComponent cannot be cast to class org.hl7.fhir.instance.model.api.IPrimitiveType (org.hl7.fhir.r4.model.Device$DeviceVersionComponent and org.hl7.fhir.instance.model.api.IPrimitiveType are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:542)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
```

This can be reproduced by running: `docker run -p 8080:8080 -e "hapi.fhir.implementationguides.who.name=who.fhir.anc-cds" -e "hapi.fhir.implementationguides.who.version=0.3.0" -e "hapi.fhir.implementationguides.who.packageUrl=https://build.fhir.org/ig/WorldHealthOrganization/smart-anc/package.tgz" -e "hapi.fhir.implementationguides.who.installMode=STORE_AND_INSTALL" hapiproject/hapi:v7.0.3` which runs on top of HAPI FHIR release 7.0.2

**Comment by jkiddo** [comment]
See also https://chat.fhir.org/#narrow/channel/179166-implementers/topic/bug.20in.20org.2Ehl7.2Efhir.2Er4.2Emodel.2EDevice.3F
