### ISSUE TITLE
Transaction control methods setAutoCommit(true), commit, rollback and setSavePoint not allowed while an XA transaction is active

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/hapi-fhir#5976]
The DatabaseSearchCacheSvcImpl DeleteRun throws exception: 
"Transaction control methods setAutoCommit(true), commit, rollback and setSavePoint not allowed while an XA transaction is active".
We are upgrading to hapi-fhir version 6.10.5. Our setup is using Atomikos as transaction manager because we need XA transactions (database and messagequeue).  

**To Reproduce**
1. Start server based on hapi-fhir jpa and configured with XA
2. Execute some searches
3. Wait until cached searched are deleted

**Expected behavior**
That the deletion of cached searches is possible when using XA transacttion manager. The problem is the unwrapping and explicit commit that has been introduced: 
https://github.com/hapifhir/hapi-fhir/blob/4ac65da2eefde6d3d660745b51252a997e52b8e0/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/cache/DatabaseSearchCacheSvcImpl.java#L223

**Stacktrace**
`Job (HAPI.ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.hibernate.exception.GenericJDBCException: error executing work]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.exception.GenericJDBCException: error executing work
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:313)
        at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1125)
        at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1112)
        at jdk.internal.reflect.GeneratedMethodAccessor328.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:362)
        at jdk.proxy2/jdk.proxy2.$Proxy268.doWork(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor328.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:315)
        at jdk.proxy2/jdk.proxy2.$Proxy268.doWork(Unknown Source)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$DeleteRun.commitOpenChanges(DatabaseSearchCacheSvcImpl.java:224)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$DeleteRun.flushDeleteMarks(DatabaseSearchCacheSvcImpl.java:213)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$DeleteRun.markDeletedInBatches(DatabaseSearchCacheSvcImpl.java:392)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$DeleteRun.lambda$run$1(DatabaseSearchCacheSvcImpl.java:352)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:401)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteInTransaction(HapiTransactionService.java:278)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecute(HapiTransactionService.java:255)
        at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder.execute(HapiTransactionService.java:492)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$DeleteRun.run(DatabaseSearchCacheSvcImpl.java:350)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl.pollForStaleSearchesAndDeleteThem(DatabaseSearchCacheSvcImpl.java:418)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$$FastClassBySpringCGLIB$$f9ac20c0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
        at ca.uhn.fhir.jpa.search.cache.DatabaseSearchCacheSvcImpl$$EnhancerBySpringCGLIB$$220171f8.pollForStaleSearchesAndDeleteThem(<generated>)
        at ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl.pollForStaleSearchesAndDeleteThem(StaleSearchDeletingSvcImpl.java:59)
        at ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl.schedulePollForStaleSearches(StaleSearchDeletingSvcImpl.java:93)
        at ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl$$FastClassBySpringCGLIB$$979cdeaa.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
        at ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl$$EnhancerBySpringCGLIB$$f1dcadf6.schedulePollForStaleSearches(<generated>)
        at ca.uhn.fhir.jpa.search.StaleSearchDeletingSvcImpl$Job.execute(StaleSearchDeletingSvcImpl.java:85)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: org.postgresql.util.PSQLException: Transaction control methods setAutoCommit(true), commit, rollback and setSavePoint not allowed while an XA transaction is active.
        at org.postgresql.xa.PGXAConnection$ConnectionHandler.invoke(PGXAConnection.java:132)
        at jdk.proxy2/jdk.proxy2.$Proxy139.commit(Unknown Source)
        at com.atomikos.jdbc.internal.AbstractJdbcConnectionProxy.commit(AbstractJdbcConnectionProxy.java:170)
        at jdk.internal.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.atomikos.util.DynamicProxySupport.callProxiedMethod(DynamicProxySupport.java:159)
        at com.atomikos.util.DynamicProxySupport.invoke(DynamicProxySupport.java:116)
        at jdk.proxy2/jdk.proxy2.$Proxy145.commit(Unknown Source)
        at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
        at org.hibernate.internal.AbstractSharedSessionContract.lambda$doWork$1(AbstractSharedSessionContract.java:1109)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:308)
        ... 46 more
`

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.10.5
 - OS: [e.g. iOS]: Linux/Kubernetes
 - Browser [e.g. chrome, safari]: NA

**Additional context**
`    @Bean
    public DataSource dataSource() throws ClassNotFoundException, NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
        ourLog.info("Initializing data source with XA");
        AtomikosDataSourceBean atomiksDataSource = new AtomikosDataSourceBean();

        atomiksDataSource.setXaDataSourceClassName("org.postgresql.xa.PGXADataSource");
`

**Comment by jamesagnew** [comment]
FWIW: We don't officially support XA in HAPI FHIR (no customer demand for
this) so we don't do any testing on XA environments. It looks like the line
in question was introduced here
<https://github.com/hapifhir/hapi-fhir/commit/757ef722792220e6e5810df6ccec3fc79638c094#diff-3da70ac83feaf74cb3040fa1f951be116d2aa203e3497816137f52cdff3d773aR224>,
as a way of increasing throughput on high volume servers.

I don't know if there is a way of detecting an XA environment
programmatically in that spot, but I suppose if so it wouldn't hurt to wrap
that statement in such a check.

**Comment by tyfoni-systematic** [comment]
OK, we have a fork on hapi-fhir, so I just revert "Clean stale search results more aggressively. (#5396)" to get the old solution which was working in our context.

**Comment by jamesagnew** [comment]
Sounds good. I'm going to close this then, as it's out of scope for the project and you have a workaround. But (to anyone reading this) please feel free to reopen if you want to submit a PR adding conditional logic around this statement.
