### ISSUE TITLE
terminology upload -  CodeSystemVersion is null

### ISSUE THREAD

**Issue by gdrouet** [hapifhir/hapi-fhir#6417]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
`hapi-fhir-cli` returns the following error when uploading ICD10: ` .InvalidRequestException: HTTP 400 : HAPI-1769: CodeSystemVersion is null`

**To Reproduce**
1. Download ICD 10 (I use the french edition here: https://smt.esante.gouv.fr/terminologie-cim-10/)
2. Run the command against my local server `hapi-fhir-cli upload-terminology -d ./dat/cim10fr2024syst_claml_20231215.xml -v r5 -t http://localhost:9090/server/DEFAULT -u 'http://hl7.org/fhir/sid/icd-10'`
3. Get the error

**Expected behavior**
All terms should be integrated

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR: 7.2.2
 - OS: Windows

**Additional context**
The service fails when checking the version of child terms.
In `TermCodeSystemStorageSvcImpl` class, I this this:

```java
		for (TermConceptParentChildLink next : theConcept.getChildren()) {
			next.setCodeSystem(theCodeSystemVersion);
			retVal +=
					validateConceptForStorage(next.getChild(), theCodeSystemVersion, theConceptsStack, theAllConcepts);
		}
```

`next.getChild()` has a method `getCodeSystemVersion()` which returns `null`. This cause the issue.
The `next.setCodeSystem(theCodeSystemVersion);` does not change the child's version.
Calling `next.setCodeSystem(theCodeSystemVersion);` would solves the problem.

**Comment by LJNIC** [comment]
Just ran into this on HAPI 7.4.0, pretty unfortunate. I guess nobody is loading ICD 10 these days?  I've loaded a basic CSV with a fake URI and just forcibly changed the URI in the database as a workaround, since it's hardcoded to detect the proper one.

**Comment by joel-bach** [comment]
With HAPI 8.8.0, I get a NullPointerException instead but I think the root cause is the same as before in that the code system version is not set for child codes in the Icd10Loader.

```
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.jpa.entity.TermCodeSystemVersion.getPid()" because "theCodeSystemVersion" is null
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:272)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:399)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:145)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:274)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:356)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1203)
	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:438)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1947)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:165)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:88)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:113)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:83)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:72)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1774)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:973)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:491)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
	... 37 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.jpa.entity.TermCodeSystemVersion.getPid()" because "theCodeSystemVersion" is null
	at ca.uhn.fhir.jpa.entity.TermConceptProperty.setCodeSystemVersion(TermConceptProperty.java:293)
	at ca.uhn.fhir.jpa.entity.TermConcept.addProperty(TermConcept.java:285)
	at ca.uhn.fhir.jpa.entity.TermConcept.addPropertyString(TermConcept.java:307)
	at ca.uhn.fhir.jpa.term.icd10.Icd10Loader.load(Icd10Loader.java:97)
	at ca.uhn.fhir.jpa.term.TermLoaderSvcImpl.loadIcd10(TermLoaderSvcImpl.java:360)
	at ca.uhn.fhir.jpa.provider.TerminologyUploaderProvider.uploadSnapshot(TerminologyUploaderProvider.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 39 common frames omitted
```
