### ISSUE TITLE
Concurrency issue in WorkerContextValidationSupportAdapter

### ISSUE THREAD

**Issue by Boereck** [hapifhir/hapi-fhir#6554]
Hi, 
after upgrading to HAPI 7.6.0 we got `ConcurrentModificationException`s in our validation test runs, which uses the same `FhirValidator` instance (which the documentation claims is thread safe) to validate many example resources in parallel. It was quite tricky to find the source of the error, due to the concurrent nature, but we are certain there is a problem in the `VersionSpecificWorkerContextWrapper`.

**Describe the bug**
The problematic function is `validateCodeInValueSet`:
https://github.com/hapifhir/hapi-fhir/blob/a999cb32c5b916d9911762656198a32d1cd24199/hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/VersionSpecificWorkerContextWrapper.java#L803-L834

In this function `.getRootValidationSupport().validateCodeInValueSet(...)` is called to get a `CodeValidationResult`. Since our root ValidationSupport is a `CachingValidationSupport`, this may return a cached object. Later it is checked if the code is valid in the CodeSystem. If this is not the case, the issues will be added to the result from the ValueSet validation, which may be a cached object!
In this case multiple parallel validations may write to the issues list of the result, causing `ConcurrentModificationException`s when reading the issue list later.

In future versions the `ValidationSupportChain` will do the caching and provoke the same problem.

Fortunately, the fix is pretty staight forward. Since the `validateCodeInValueSet` returns a result object, in the 
```java
if (codeSystemResult != null) {
	//...
}
```
block, `result` can be assigned to a copy of `result`. This can be implemented in `VersionSpecificWorkerContextWrapper` for the moment, but ideally `IValidationSupport.CodeValidationResult` could provide a copy constructor, or a copy instance method in future. However this class is in the `org.hl7.fhir.core` project, so this would have to be added upstream.
Since all objects referenced from `IValidationSupport.CodeValidationResult` (apart from the list-fields) are immutable, it would suffice to do a shallow copy, and just create list copies of the list-fields.

If wanted, we can provide a PR to fix this issue. We already tried the change and we did not face any `ConcurrentModificationException` after the change. We could also back-port this issue to the 7.6.0 stream, we just need to know against which branch the PR should go.

**To Reproduce**
This behavior is extremely tricky to reproduce, due to the concurrent nature. However, when validating a resource using a code in a place with with binding to a value set, that is not actually included in any CodeSystem referenced in the ValueSet, and doing so over and over in parallel with the same validator object, this might be triggered.

**Expected behavior**
No `ConcurrentModificationException` and and no multiplying issues on code in VS validation failures.

**Environment (please complete the following information):**
 - HAPI FHIR Version 7.6.0 (also tested on 7.7.14-SNAPSHOT)

**Comment by Boereck** [comment]
I opened PR #6648 for this issue.
It seems the 7.6.x releases are created from branch `rel_7_6`. It was easy to port the fix on that branch as well. I can Open a PR for this branch as well, If this is of interest.

**Comment by Boereck** [comment]
BTW: The issue was apparently introduced via PR
#5772 in [this](https://github.com/hapifhir/hapi-fhir/pull/5772/commits/a5f3890c337d67ac1302e529a7fae59831feccaf#diff-d8e47a5bb9c7cc151bf6f1bb31f822f76a7a5384b38a9c8765986bfc4c7f11afR797-R809) change. @dotasek , since you seems to be the author of the change, maybe you want to review this issue and the PR? Thanks!

**Comment by jamesagnew** [comment]
Closing, as https://github.com/hapifhir/hapi-fhir/pull/6648 has now been merged.

**Comment by madduci** [comment]
I'm getting the same bug with HAPI 8.4.0 now, with the following output:

```java
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
	at org.hl7.fhir.common.hapi.validation.validator.WorkerContextValidationSupportAdapter.getIssuesForCodeValidation(WorkerContextValidationSupportAdapter.java:380)
	at org.hl7.fhir.common.hapi.validation.validator.WorkerContextValidationSupportAdapter.convertValidationResult(WorkerContextValidationSupportAdapter.java:366)
	at org.hl7.fhir.common.hapi.validation.validator.WorkerContextValidationSupportAdapter.doValidation(WorkerContextValidationSupportAdapter.java:838)
	at org.hl7.fhir.common.hapi.validation.validator.WorkerContextValidationSupportAdapter.validateCode(WorkerContextValidationSupportAdapter.java:787)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkCodeOnServer(InstanceValidator.java:8411)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkPrimitiveBinding(InstanceValidator.java:4043)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkPrimitive(InstanceValidator.java:3413)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:7215)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:7044)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6972)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:7365)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:7044)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6972)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:6402)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:6154)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:8183)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkReference(InstanceValidator.java:4701)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:7240)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:7044)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6972)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:6402)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:6154)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:8183)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateContains(InstanceValidator.java:6795)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:7260)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:7044)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6972)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:7284)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:7044)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6972)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:6402)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:6154)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:8183)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:1017)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:835)
	at org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.validate(ValidatorWrapper.java:186)
	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validate(FhirInstanceValidator.java:256)
	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:23)
	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:61)
	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:28)
	at ca.uhn.fhir.validation.FhirValidator.validateResource(FhirValidator.java:357)
	at ca.uhn.fhir.validation.FhirValidator.doValidate(FhirValidator.java:273)
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:241)
```

The FHIR Validator is simply constructed and called with the single `ValidationOptions` containing the FHIR Profile to be used for validation.

**Comment by Boereck** [comment]
The fix was pulled after the 8.4.0 release branch was created. As you can see [here on 8.4.0](https://github.com/hapifhir/hapi-fhir/blob/v8.4.0/hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/WorkerContextValidationSupportAdapter.java#L901) vs. [here on master](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/WorkerContextValidationSupportAdapter.java#L901). 
It looks like it will be released with the upcoming version 8.6.0.

**Comment by madduci** [comment]
ok thanks!
